// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	node "github.com/pastelnetwork/gonode/walletnode/node"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Connect provides a mock function with given fields: ctx, address
func (_m *Client) Connect(ctx context.Context, address string) (node.Connection, error) {
	ret := _m.Called(ctx, address)

	var r0 node.Connection
	if rf, ok := ret.Get(0).(func(context.Context, string) node.Connection); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.Connection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
