// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_wn.proto

package walletnode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionRequest struct {
	IsPrimary            bool     `protobuf:"varint,1,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{0}
}

func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(m, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

type SessionReply struct {
	SessID               string   `protobuf:"bytes,1,opt,name=sessID,proto3" json:"sessID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionReply) Reset()         { *m = SessionReply{} }
func (m *SessionReply) String() string { return proto.CompactTextString(m) }
func (*SessionReply) ProtoMessage()    {}
func (*SessionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{1}
}

func (m *SessionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionReply.Unmarshal(m, b)
}
func (m *SessionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionReply.Marshal(b, m, deterministic)
}
func (m *SessionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionReply.Merge(m, src)
}
func (m *SessionReply) XXX_Size() int {
	return xxx_messageInfo_SessionReply.Size(m)
}
func (m *SessionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionReply proto.InternalMessageInfo

func (m *SessionReply) GetSessID() string {
	if m != nil {
		return m.SessID
	}
	return ""
}

type AcceptedNodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptedNodesRequest) Reset()         { *m = AcceptedNodesRequest{} }
func (m *AcceptedNodesRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptedNodesRequest) ProtoMessage()    {}
func (*AcceptedNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{2}
}

func (m *AcceptedNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptedNodesRequest.Unmarshal(m, b)
}
func (m *AcceptedNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptedNodesRequest.Marshal(b, m, deterministic)
}
func (m *AcceptedNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptedNodesRequest.Merge(m, src)
}
func (m *AcceptedNodesRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptedNodesRequest.Size(m)
}
func (m *AcceptedNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptedNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptedNodesRequest proto.InternalMessageInfo

type AcceptedNodesReply struct {
	Peers                []*AcceptedNodesReply_Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AcceptedNodesReply) Reset()         { *m = AcceptedNodesReply{} }
func (m *AcceptedNodesReply) String() string { return proto.CompactTextString(m) }
func (*AcceptedNodesReply) ProtoMessage()    {}
func (*AcceptedNodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{3}
}

func (m *AcceptedNodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptedNodesReply.Unmarshal(m, b)
}
func (m *AcceptedNodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptedNodesReply.Marshal(b, m, deterministic)
}
func (m *AcceptedNodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptedNodesReply.Merge(m, src)
}
func (m *AcceptedNodesReply) XXX_Size() int {
	return xxx_messageInfo_AcceptedNodesReply.Size(m)
}
func (m *AcceptedNodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptedNodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptedNodesReply proto.InternalMessageInfo

func (m *AcceptedNodesReply) GetPeers() []*AcceptedNodesReply_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type AcceptedNodesReply_Peer struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptedNodesReply_Peer) Reset()         { *m = AcceptedNodesReply_Peer{} }
func (m *AcceptedNodesReply_Peer) String() string { return proto.CompactTextString(m) }
func (*AcceptedNodesReply_Peer) ProtoMessage()    {}
func (*AcceptedNodesReply_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{3, 0}
}

func (m *AcceptedNodesReply_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptedNodesReply_Peer.Unmarshal(m, b)
}
func (m *AcceptedNodesReply_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptedNodesReply_Peer.Marshal(b, m, deterministic)
}
func (m *AcceptedNodesReply_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptedNodesReply_Peer.Merge(m, src)
}
func (m *AcceptedNodesReply_Peer) XXX_Size() int {
	return xxx_messageInfo_AcceptedNodesReply_Peer.Size(m)
}
func (m *AcceptedNodesReply_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptedNodesReply_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptedNodesReply_Peer proto.InternalMessageInfo

func (m *AcceptedNodesReply_Peer) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type ConnectToRequest struct {
	SessID               string   `protobuf:"bytes,1,opt,name=sessID,proto3" json:"sessID,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToRequest) Reset()         { *m = ConnectToRequest{} }
func (m *ConnectToRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectToRequest) ProtoMessage()    {}
func (*ConnectToRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{4}
}

func (m *ConnectToRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToRequest.Unmarshal(m, b)
}
func (m *ConnectToRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToRequest.Marshal(b, m, deterministic)
}
func (m *ConnectToRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToRequest.Merge(m, src)
}
func (m *ConnectToRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectToRequest.Size(m)
}
func (m *ConnectToRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToRequest proto.InternalMessageInfo

func (m *ConnectToRequest) GetSessID() string {
	if m != nil {
		return m.SessID
	}
	return ""
}

func (m *ConnectToRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type ConnectToReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToReply) Reset()         { *m = ConnectToReply{} }
func (m *ConnectToReply) String() string { return proto.CompactTextString(m) }
func (*ConnectToReply) ProtoMessage()    {}
func (*ConnectToReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{5}
}

func (m *ConnectToReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToReply.Unmarshal(m, b)
}
func (m *ConnectToReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToReply.Marshal(b, m, deterministic)
}
func (m *ConnectToReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToReply.Merge(m, src)
}
func (m *ConnectToReply) XXX_Size() int {
	return xxx_messageInfo_ConnectToReply.Size(m)
}
func (m *ConnectToReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToReply proto.InternalMessageInfo

type MeshNodesRequest struct {
	Nodes                []*MeshNodesRequest_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MeshNodesRequest) Reset()         { *m = MeshNodesRequest{} }
func (m *MeshNodesRequest) String() string { return proto.CompactTextString(m) }
func (*MeshNodesRequest) ProtoMessage()    {}
func (*MeshNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{6}
}

func (m *MeshNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshNodesRequest.Unmarshal(m, b)
}
func (m *MeshNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshNodesRequest.Marshal(b, m, deterministic)
}
func (m *MeshNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshNodesRequest.Merge(m, src)
}
func (m *MeshNodesRequest) XXX_Size() int {
	return xxx_messageInfo_MeshNodesRequest.Size(m)
}
func (m *MeshNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MeshNodesRequest proto.InternalMessageInfo

func (m *MeshNodesRequest) GetNodes() []*MeshNodesRequest_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type MeshNodesRequest_Node struct {
	SessID               string   `protobuf:"bytes,1,opt,name=sessID,proto3" json:"sessID,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshNodesRequest_Node) Reset()         { *m = MeshNodesRequest_Node{} }
func (m *MeshNodesRequest_Node) String() string { return proto.CompactTextString(m) }
func (*MeshNodesRequest_Node) ProtoMessage()    {}
func (*MeshNodesRequest_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{6, 0}
}

func (m *MeshNodesRequest_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshNodesRequest_Node.Unmarshal(m, b)
}
func (m *MeshNodesRequest_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshNodesRequest_Node.Marshal(b, m, deterministic)
}
func (m *MeshNodesRequest_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshNodesRequest_Node.Merge(m, src)
}
func (m *MeshNodesRequest_Node) XXX_Size() int {
	return xxx_messageInfo_MeshNodesRequest_Node.Size(m)
}
func (m *MeshNodesRequest_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshNodesRequest_Node.DiscardUnknown(m)
}

var xxx_messageInfo_MeshNodesRequest_Node proto.InternalMessageInfo

func (m *MeshNodesRequest_Node) GetSessID() string {
	if m != nil {
		return m.SessID
	}
	return ""
}

func (m *MeshNodesRequest_Node) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type MeshNodesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshNodesReply) Reset()         { *m = MeshNodesReply{} }
func (m *MeshNodesReply) String() string { return proto.CompactTextString(m) }
func (*MeshNodesReply) ProtoMessage()    {}
func (*MeshNodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{7}
}

func (m *MeshNodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshNodesReply.Unmarshal(m, b)
}
func (m *MeshNodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshNodesReply.Marshal(b, m, deterministic)
}
func (m *MeshNodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshNodesReply.Merge(m, src)
}
func (m *MeshNodesReply) XXX_Size() int {
	return xxx_messageInfo_MeshNodesReply.Size(m)
}
func (m *MeshNodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshNodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_MeshNodesReply proto.InternalMessageInfo

type SendRegMetadataRequest struct {
	CreatorPastelID      string   `protobuf:"bytes,1,opt,name=creatorPastelID,proto3" json:"creatorPastelID,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BurnTxid             string   `protobuf:"bytes,3,opt,name=burn_txid,json=burnTxid,proto3" json:"burn_txid,omitempty"`
	BlockHeight          string   `protobuf:"bytes,4,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GroupId              string   `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CollectionTxid       string   `protobuf:"bytes,7,opt,name=collection_txid,json=collectionTxid,proto3" json:"collection_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRegMetadataRequest) Reset()         { *m = SendRegMetadataRequest{} }
func (m *SendRegMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*SendRegMetadataRequest) ProtoMessage()    {}
func (*SendRegMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{8}
}

func (m *SendRegMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRegMetadataRequest.Unmarshal(m, b)
}
func (m *SendRegMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRegMetadataRequest.Marshal(b, m, deterministic)
}
func (m *SendRegMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRegMetadataRequest.Merge(m, src)
}
func (m *SendRegMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_SendRegMetadataRequest.Size(m)
}
func (m *SendRegMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRegMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRegMetadataRequest proto.InternalMessageInfo

func (m *SendRegMetadataRequest) GetCreatorPastelID() string {
	if m != nil {
		return m.CreatorPastelID
	}
	return ""
}

func (m *SendRegMetadataRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *SendRegMetadataRequest) GetBurnTxid() string {
	if m != nil {
		return m.BurnTxid
	}
	return ""
}

func (m *SendRegMetadataRequest) GetBlockHeight() string {
	if m != nil {
		return m.BlockHeight
	}
	return ""
}

func (m *SendRegMetadataRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *SendRegMetadataRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *SendRegMetadataRequest) GetCollectionTxid() string {
	if m != nil {
		return m.CollectionTxid
	}
	return ""
}

type SendRegMetadataReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRegMetadataReply) Reset()         { *m = SendRegMetadataReply{} }
func (m *SendRegMetadataReply) String() string { return proto.CompactTextString(m) }
func (*SendRegMetadataReply) ProtoMessage()    {}
func (*SendRegMetadataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{9}
}

func (m *SendRegMetadataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRegMetadataReply.Unmarshal(m, b)
}
func (m *SendRegMetadataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRegMetadataReply.Marshal(b, m, deterministic)
}
func (m *SendRegMetadataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRegMetadataReply.Merge(m, src)
}
func (m *SendRegMetadataReply) XXX_Size() int {
	return xxx_messageInfo_SendRegMetadataReply.Size(m)
}
func (m *SendRegMetadataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRegMetadataReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendRegMetadataReply proto.InternalMessageInfo

type ProbeImageRequest struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeImageRequest) Reset()         { *m = ProbeImageRequest{} }
func (m *ProbeImageRequest) String() string { return proto.CompactTextString(m) }
func (*ProbeImageRequest) ProtoMessage()    {}
func (*ProbeImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{10}
}

func (m *ProbeImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeImageRequest.Unmarshal(m, b)
}
func (m *ProbeImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeImageRequest.Marshal(b, m, deterministic)
}
func (m *ProbeImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeImageRequest.Merge(m, src)
}
func (m *ProbeImageRequest) XXX_Size() int {
	return xxx_messageInfo_ProbeImageRequest.Size(m)
}
func (m *ProbeImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeImageRequest proto.InternalMessageInfo

func (m *ProbeImageRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ProbeImageReply struct {
	CompressedSignedDDAndFingerprints []byte   `protobuf:"bytes,1,opt,name=compressedSignedDDAndFingerprints,proto3" json:"compressedSignedDDAndFingerprints,omitempty"`
	IsValidBurnTxid                   bool     `protobuf:"varint,2,opt,name=is_valid_burn_txid,json=isValidBurnTxid,proto3" json:"is_valid_burn_txid,omitempty"`
	ErrString                         string   `protobuf:"bytes,3,opt,name=err_string,json=errString,proto3" json:"err_string,omitempty"`
	IsExisting                        bool     `protobuf:"varint,4,opt,name=is_existing,json=isExisting,proto3" json:"is_existing,omitempty"`
	XXX_NoUnkeyedLiteral              struct{} `json:"-"`
	XXX_unrecognized                  []byte   `json:"-"`
	XXX_sizecache                     int32    `json:"-"`
}

func (m *ProbeImageReply) Reset()         { *m = ProbeImageReply{} }
func (m *ProbeImageReply) String() string { return proto.CompactTextString(m) }
func (*ProbeImageReply) ProtoMessage()    {}
func (*ProbeImageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{11}
}

func (m *ProbeImageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeImageReply.Unmarshal(m, b)
}
func (m *ProbeImageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeImageReply.Marshal(b, m, deterministic)
}
func (m *ProbeImageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeImageReply.Merge(m, src)
}
func (m *ProbeImageReply) XXX_Size() int {
	return xxx_messageInfo_ProbeImageReply.Size(m)
}
func (m *ProbeImageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeImageReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeImageReply proto.InternalMessageInfo

func (m *ProbeImageReply) GetCompressedSignedDDAndFingerprints() []byte {
	if m != nil {
		return m.CompressedSignedDDAndFingerprints
	}
	return nil
}

func (m *ProbeImageReply) GetIsValidBurnTxid() bool {
	if m != nil {
		return m.IsValidBurnTxid
	}
	return false
}

func (m *ProbeImageReply) GetErrString() string {
	if m != nil {
		return m.ErrString
	}
	return ""
}

func (m *ProbeImageReply) GetIsExisting() bool {
	if m != nil {
		return m.IsExisting
	}
	return false
}

type EncoderParameters struct {
	Oti                  []byte   `protobuf:"bytes,1,opt,name=oti,proto3" json:"oti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncoderParameters) Reset()         { *m = EncoderParameters{} }
func (m *EncoderParameters) String() string { return proto.CompactTextString(m) }
func (*EncoderParameters) ProtoMessage()    {}
func (*EncoderParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{12}
}

func (m *EncoderParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncoderParameters.Unmarshal(m, b)
}
func (m *EncoderParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncoderParameters.Marshal(b, m, deterministic)
}
func (m *EncoderParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncoderParameters.Merge(m, src)
}
func (m *EncoderParameters) XXX_Size() int {
	return xxx_messageInfo_EncoderParameters.Size(m)
}
func (m *EncoderParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_EncoderParameters.DiscardUnknown(m)
}

var xxx_messageInfo_EncoderParameters proto.InternalMessageInfo

func (m *EncoderParameters) GetOti() []byte {
	if m != nil {
		return m.Oti
	}
	return nil
}

type SendSignedActionTicketReply struct {
	ActionRegTxid        string   `protobuf:"bytes,1,opt,name=action_reg_txid,json=actionRegTxid,proto3" json:"action_reg_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSignedActionTicketReply) Reset()         { *m = SendSignedActionTicketReply{} }
func (m *SendSignedActionTicketReply) String() string { return proto.CompactTextString(m) }
func (*SendSignedActionTicketReply) ProtoMessage()    {}
func (*SendSignedActionTicketReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{13}
}

func (m *SendSignedActionTicketReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSignedActionTicketReply.Unmarshal(m, b)
}
func (m *SendSignedActionTicketReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSignedActionTicketReply.Marshal(b, m, deterministic)
}
func (m *SendSignedActionTicketReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSignedActionTicketReply.Merge(m, src)
}
func (m *SendSignedActionTicketReply) XXX_Size() int {
	return xxx_messageInfo_SendSignedActionTicketReply.Size(m)
}
func (m *SendSignedActionTicketReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSignedActionTicketReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendSignedActionTicketReply proto.InternalMessageInfo

func (m *SendSignedActionTicketReply) GetActionRegTxid() string {
	if m != nil {
		return m.ActionRegTxid
	}
	return ""
}

type SendActionActRequest struct {
	ActionRegTxid        string   `protobuf:"bytes,1,opt,name=action_reg_txid,json=actionRegTxid,proto3" json:"action_reg_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActionActRequest) Reset()         { *m = SendActionActRequest{} }
func (m *SendActionActRequest) String() string { return proto.CompactTextString(m) }
func (*SendActionActRequest) ProtoMessage()    {}
func (*SendActionActRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{14}
}

func (m *SendActionActRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActionActRequest.Unmarshal(m, b)
}
func (m *SendActionActRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActionActRequest.Marshal(b, m, deterministic)
}
func (m *SendActionActRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActionActRequest.Merge(m, src)
}
func (m *SendActionActRequest) XXX_Size() int {
	return xxx_messageInfo_SendActionActRequest.Size(m)
}
func (m *SendActionActRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActionActRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendActionActRequest proto.InternalMessageInfo

func (m *SendActionActRequest) GetActionRegTxid() string {
	if m != nil {
		return m.ActionRegTxid
	}
	return ""
}

type SendActionActReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActionActReply) Reset()         { *m = SendActionActReply{} }
func (m *SendActionActReply) String() string { return proto.CompactTextString(m) }
func (*SendActionActReply) ProtoMessage()    {}
func (*SendActionActReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{15}
}

func (m *SendActionActReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActionActReply.Unmarshal(m, b)
}
func (m *SendActionActReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActionActReply.Marshal(b, m, deterministic)
}
func (m *SendActionActReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActionActReply.Merge(m, src)
}
func (m *SendActionActReply) XXX_Size() int {
	return xxx_messageInfo_SendActionActReply.Size(m)
}
func (m *SendActionActReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActionActReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendActionActReply proto.InternalMessageInfo

type GetDBHashRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDBHashRequest) Reset()         { *m = GetDBHashRequest{} }
func (m *GetDBHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetDBHashRequest) ProtoMessage()    {}
func (*GetDBHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{16}
}

func (m *GetDBHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBHashRequest.Unmarshal(m, b)
}
func (m *GetDBHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBHashRequest.Marshal(b, m, deterministic)
}
func (m *GetDBHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBHashRequest.Merge(m, src)
}
func (m *GetDBHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetDBHashRequest.Size(m)
}
func (m *GetDBHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBHashRequest proto.InternalMessageInfo

type DBHashReply struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBHashReply) Reset()         { *m = DBHashReply{} }
func (m *DBHashReply) String() string { return proto.CompactTextString(m) }
func (*DBHashReply) ProtoMessage()    {}
func (*DBHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{17}
}

func (m *DBHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBHashReply.Unmarshal(m, b)
}
func (m *DBHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBHashReply.Marshal(b, m, deterministic)
}
func (m *DBHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBHashReply.Merge(m, src)
}
func (m *DBHashReply) XXX_Size() int {
	return xxx_messageInfo_DBHashReply.Size(m)
}
func (m *DBHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DBHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_DBHashReply proto.InternalMessageInfo

func (m *DBHashReply) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type DDServerStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DDServerStatsRequest) Reset()         { *m = DDServerStatsRequest{} }
func (m *DDServerStatsRequest) String() string { return proto.CompactTextString(m) }
func (*DDServerStatsRequest) ProtoMessage()    {}
func (*DDServerStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{18}
}

func (m *DDServerStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DDServerStatsRequest.Unmarshal(m, b)
}
func (m *DDServerStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DDServerStatsRequest.Marshal(b, m, deterministic)
}
func (m *DDServerStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DDServerStatsRequest.Merge(m, src)
}
func (m *DDServerStatsRequest) XXX_Size() int {
	return xxx_messageInfo_DDServerStatsRequest.Size(m)
}
func (m *DDServerStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DDServerStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DDServerStatsRequest proto.InternalMessageInfo

type DDServerStatsReply struct {
	MaxConcurrent        int32    `protobuf:"varint,1,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Executing            int32    `protobuf:"varint,2,opt,name=executing,proto3" json:"executing,omitempty"`
	WaitingInQueue       int32    `protobuf:"varint,3,opt,name=waiting_in_queue,json=waitingInQueue,proto3" json:"waiting_in_queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DDServerStatsReply) Reset()         { *m = DDServerStatsReply{} }
func (m *DDServerStatsReply) String() string { return proto.CompactTextString(m) }
func (*DDServerStatsReply) ProtoMessage()    {}
func (*DDServerStatsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{19}
}

func (m *DDServerStatsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DDServerStatsReply.Unmarshal(m, b)
}
func (m *DDServerStatsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DDServerStatsReply.Marshal(b, m, deterministic)
}
func (m *DDServerStatsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DDServerStatsReply.Merge(m, src)
}
func (m *DDServerStatsReply) XXX_Size() int {
	return xxx_messageInfo_DDServerStatsReply.Size(m)
}
func (m *DDServerStatsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DDServerStatsReply.DiscardUnknown(m)
}

var xxx_messageInfo_DDServerStatsReply proto.InternalMessageInfo

func (m *DDServerStatsReply) GetMaxConcurrent() int32 {
	if m != nil {
		return m.MaxConcurrent
	}
	return 0
}

func (m *DDServerStatsReply) GetExecuting() int32 {
	if m != nil {
		return m.Executing
	}
	return 0
}

func (m *DDServerStatsReply) GetWaitingInQueue() int32 {
	if m != nil {
		return m.WaitingInQueue
	}
	return 0
}

type GetTopMNsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopMNsRequest) Reset()         { *m = GetTopMNsRequest{} }
func (m *GetTopMNsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopMNsRequest) ProtoMessage()    {}
func (*GetTopMNsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{20}
}

func (m *GetTopMNsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopMNsRequest.Unmarshal(m, b)
}
func (m *GetTopMNsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopMNsRequest.Marshal(b, m, deterministic)
}
func (m *GetTopMNsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopMNsRequest.Merge(m, src)
}
func (m *GetTopMNsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopMNsRequest.Size(m)
}
func (m *GetTopMNsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopMNsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopMNsRequest proto.InternalMessageInfo

type GetTopMNsReply struct {
	MnTopList            []string `protobuf:"bytes,1,rep,name=mn_top_list,json=mnTopList,proto3" json:"mn_top_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopMNsReply) Reset()         { *m = GetTopMNsReply{} }
func (m *GetTopMNsReply) String() string { return proto.CompactTextString(m) }
func (*GetTopMNsReply) ProtoMessage()    {}
func (*GetTopMNsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_be3d8ea5a26e87bf, []int{21}
}

func (m *GetTopMNsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopMNsReply.Unmarshal(m, b)
}
func (m *GetTopMNsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopMNsReply.Marshal(b, m, deterministic)
}
func (m *GetTopMNsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopMNsReply.Merge(m, src)
}
func (m *GetTopMNsReply) XXX_Size() int {
	return xxx_messageInfo_GetTopMNsReply.Size(m)
}
func (m *GetTopMNsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopMNsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopMNsReply proto.InternalMessageInfo

func (m *GetTopMNsReply) GetMnTopList() []string {
	if m != nil {
		return m.MnTopList
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionRequest)(nil), "walletnode.SessionRequest")
	proto.RegisterType((*SessionReply)(nil), "walletnode.SessionReply")
	proto.RegisterType((*AcceptedNodesRequest)(nil), "walletnode.AcceptedNodesRequest")
	proto.RegisterType((*AcceptedNodesReply)(nil), "walletnode.AcceptedNodesReply")
	proto.RegisterType((*AcceptedNodesReply_Peer)(nil), "walletnode.AcceptedNodesReply.Peer")
	proto.RegisterType((*ConnectToRequest)(nil), "walletnode.ConnectToRequest")
	proto.RegisterType((*ConnectToReply)(nil), "walletnode.ConnectToReply")
	proto.RegisterType((*MeshNodesRequest)(nil), "walletnode.MeshNodesRequest")
	proto.RegisterType((*MeshNodesRequest_Node)(nil), "walletnode.MeshNodesRequest.Node")
	proto.RegisterType((*MeshNodesReply)(nil), "walletnode.MeshNodesReply")
	proto.RegisterType((*SendRegMetadataRequest)(nil), "walletnode.SendRegMetadataRequest")
	proto.RegisterType((*SendRegMetadataReply)(nil), "walletnode.SendRegMetadataReply")
	proto.RegisterType((*ProbeImageRequest)(nil), "walletnode.ProbeImageRequest")
	proto.RegisterType((*ProbeImageReply)(nil), "walletnode.ProbeImageReply")
	proto.RegisterType((*EncoderParameters)(nil), "walletnode.EncoderParameters")
	proto.RegisterType((*SendSignedActionTicketReply)(nil), "walletnode.SendSignedActionTicketReply")
	proto.RegisterType((*SendActionActRequest)(nil), "walletnode.SendActionActRequest")
	proto.RegisterType((*SendActionActReply)(nil), "walletnode.SendActionActReply")
	proto.RegisterType((*GetDBHashRequest)(nil), "walletnode.GetDBHashRequest")
	proto.RegisterType((*DBHashReply)(nil), "walletnode.DBHashReply")
	proto.RegisterType((*DDServerStatsRequest)(nil), "walletnode.DDServerStatsRequest")
	proto.RegisterType((*DDServerStatsReply)(nil), "walletnode.DDServerStatsReply")
	proto.RegisterType((*GetTopMNsRequest)(nil), "walletnode.GetTopMNsRequest")
	proto.RegisterType((*GetTopMNsReply)(nil), "walletnode.GetTopMNsReply")
}

func init() { proto.RegisterFile("common_wn.proto", fileDescriptor_be3d8ea5a26e87bf) }

var fileDescriptor_be3d8ea5a26e87bf = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x8f, 0xda, 0x46,
	0x10, 0x16, 0x1c, 0xdc, 0x1d, 0x43, 0x02, 0x64, 0x15, 0x9d, 0x68, 0xd2, 0xa4, 0x77, 0xae, 0x92,
	0x22, 0x55, 0x85, 0x28, 0x95, 0x5a, 0xf5, 0xa5, 0x12, 0x84, 0x6b, 0x8b, 0x94, 0x8b, 0xa8, 0x41,
	0x7d, 0xe8, 0x8b, 0xb5, 0xd8, 0x23, 0xb3, 0x3a, 0x7b, 0xd7, 0xb7, 0xbb, 0x3e, 0xe0, 0xb1, 0xba,
	0xbf, 0xd7, 0x1f, 0x55, 0xed, 0xae, 0x0d, 0x2e, 0xa7, 0xaa, 0x55, 0xdf, 0x3c, 0xdf, 0xcc, 0x7e,
	0xfb, 0xed, 0x37, 0xe3, 0x81, 0x6e, 0x28, 0xd2, 0x54, 0xf0, 0x60, 0xc3, 0x87, 0x99, 0x14, 0x5a,
	0x10, 0xd8, 0xd0, 0x24, 0x41, 0xcd, 0x45, 0x84, 0xde, 0x08, 0x3a, 0x0b, 0x54, 0x8a, 0x09, 0xee,
	0xe3, 0x5d, 0x8e, 0x4a, 0x93, 0x57, 0x00, 0x4c, 0x05, 0x99, 0x64, 0x29, 0x95, 0xbb, 0x7e, 0xed,
	0xb2, 0x36, 0x38, 0xf7, 0x5b, 0x4c, 0xcd, 0x1d, 0xe0, 0xbd, 0x85, 0x27, 0xfb, 0x03, 0x59, 0xb2,
	0x23, 0x17, 0x70, 0xaa, 0x50, 0xa9, 0xd9, 0xd4, 0x96, 0xb6, 0xfc, 0x22, 0xf2, 0x2e, 0xe0, 0xf9,
	0x38, 0x0c, 0x31, 0xd3, 0x18, 0x7d, 0x12, 0x11, 0xaa, 0x82, 0xde, 0x13, 0x40, 0x8e, 0x70, 0xc3,
	0xf2, 0x03, 0x34, 0x33, 0x44, 0xa9, 0xfa, 0xb5, 0xcb, 0x93, 0x41, 0xfb, 0xfd, 0x97, 0xc3, 0x83,
	0xc4, 0xe1, 0xe3, 0xf2, 0xe1, 0x1c, 0x51, 0xfa, 0xee, 0xc4, 0x8b, 0xd7, 0xd0, 0x30, 0xa1, 0x11,
	0x62, 0xca, 0x0f, 0x42, 0x5c, 0xe4, 0x4d, 0xa0, 0xf7, 0x41, 0x70, 0x8e, 0xa1, 0x5e, 0x8a, 0xf2,
	0x8d, 0xff, 0x20, 0xba, 0xc2, 0x51, 0xff, 0x1b, 0x47, 0x0f, 0x3a, 0x15, 0x8e, 0x2c, 0xd9, 0x79,
	0x0f, 0x35, 0xe8, 0xdd, 0xa0, 0x5a, 0x57, 0xdf, 0x46, 0xbe, 0x87, 0xa6, 0x39, 0x50, 0xbe, 0xe2,
	0xaa, 0xfa, 0x8a, 0xe3, 0xe2, 0xa1, 0x09, 0x7c, 0x57, 0xff, 0xe2, 0x3b, 0x68, 0x98, 0xf0, 0xff,
	0xe8, 0xaa, 0xf0, 0x1a, 0x5d, 0x7f, 0xd4, 0xe1, 0x62, 0x81, 0x3c, 0xf2, 0x31, 0xbe, 0x41, 0x4d,
	0x23, 0xaa, 0x69, 0xa9, 0x6e, 0x00, 0xdd, 0x50, 0x22, 0xd5, 0x42, 0xce, 0xa9, 0xd2, 0x98, 0xec,
	0x6f, 0x39, 0x86, 0xc9, 0xe7, 0xd0, 0x5a, 0x25, 0x22, 0xbc, 0xfd, 0x85, 0xaa, 0x75, 0x71, 0xe3,
	0x01, 0x20, 0x2f, 0xa1, 0xb5, 0xca, 0x25, 0x0f, 0xf4, 0x96, 0x45, 0xfd, 0x13, 0x9b, 0x3d, 0x37,
	0xc0, 0x72, 0xcb, 0x22, 0x72, 0x09, 0x6d, 0x57, 0x89, 0x2c, 0x5e, 0xeb, 0x7e, 0xc3, 0xa6, 0xab,
	0x90, 0x21, 0xd7, 0x2c, 0x45, 0xa5, 0x69, 0x9a, 0xf5, 0x9b, 0x8e, 0x7c, 0x0f, 0x90, 0xcf, 0xe0,
	0x3c, 0x96, 0x22, 0xcf, 0x02, 0x16, 0xf5, 0x4f, 0x6d, 0xf2, 0xcc, 0xc6, 0xb3, 0x88, 0x7c, 0x65,
	0x26, 0x39, 0x49, 0x30, 0xd4, 0x4c, 0x14, 0xb7, 0x9f, 0xd9, 0x8a, 0xce, 0x01, 0x36, 0x1a, 0xcc,
	0xe8, 0x3d, 0xb2, 0xc0, 0x78, 0xf3, 0x0d, 0x3c, 0x9b, 0x4b, 0xb1, 0xc2, 0x59, 0x4a, 0x63, 0x2c,
	0x5d, 0xe9, 0xc3, 0x59, 0x46, 0x77, 0x89, 0xa0, 0x91, 0x75, 0xe3, 0x89, 0x5f, 0x86, 0xde, 0x9f,
	0x35, 0xe8, 0x56, 0xeb, 0xcd, 0x9c, 0x7e, 0x84, 0xab, 0x50, 0xa4, 0x99, 0x44, 0xa5, 0x30, 0x5a,
	0xb0, 0x98, 0x63, 0x34, 0x9d, 0x8e, 0x79, 0xf4, 0x13, 0xe3, 0x31, 0xca, 0x4c, 0x32, 0xae, 0x55,
	0xc1, 0xf3, 0xef, 0x85, 0xe4, 0x6b, 0x20, 0x4c, 0x05, 0xf7, 0x34, 0x61, 0x51, 0x70, 0xb0, 0xb4,
	0x6e, 0x7f, 0xb9, 0x2e, 0x53, 0xbf, 0x99, 0xc4, 0xa4, 0x74, 0xf6, 0x15, 0x00, 0x4a, 0x19, 0x28,
	0x2d, 0x19, 0x8f, 0x0b, 0xdf, 0x5b, 0x28, 0xe5, 0xc2, 0x02, 0xe4, 0x0b, 0x68, 0x33, 0x15, 0xe0,
	0x96, 0x29, 0x6d, 0xf2, 0x0d, 0x4b, 0x02, 0x4c, 0x5d, 0x17, 0x88, 0xf7, 0x06, 0x9e, 0x5d, 0xf3,
	0x50, 0x44, 0x28, 0xe7, 0x54, 0xd2, 0x14, 0x35, 0x4a, 0x45, 0x7a, 0x70, 0x22, 0x34, 0x2b, 0x14,
	0x9b, 0x4f, 0xef, 0x1a, 0x5e, 0x1a, 0xf3, 0x9c, 0xe4, 0xb1, 0x33, 0x95, 0x85, 0xb7, 0xa8, 0x9d,
	0x01, 0x6f, 0xa1, 0x4b, 0x5d, 0x03, 0x24, 0xc6, 0x4e, 0xaf, 0x1b, 0xa2, 0xa7, 0x0e, 0xf6, 0x31,
	0xb6, 0x3d, 0xf8, 0xd1, 0xf5, 0xc0, 0x11, 0x8c, 0x43, 0x5d, 0xda, 0xfd, 0x5f, 0xcf, 0x3f, 0x07,
	0x72, 0x74, 0xde, 0x74, 0x90, 0x40, 0xef, 0x67, 0xd4, 0xd3, 0x89, 0x99, 0xc3, 0x72, 0xa1, 0x5c,
	0x41, 0xbb, 0x04, 0x8c, 0x40, 0x02, 0x8d, 0xb5, 0x19, 0x5b, 0xc7, 0x6a, 0xbf, 0xcd, 0x40, 0x4c,
	0xa7, 0x0b, 0x94, 0xf7, 0x28, 0x17, 0x9a, 0xea, 0xfd, 0x2e, 0x7a, 0xa8, 0x01, 0x39, 0x4a, 0x18,
	0x8a, 0x37, 0xd0, 0x49, 0xe9, 0x36, 0x08, 0x05, 0x0f, 0x73, 0x29, 0x91, 0x6b, 0x4b, 0xd6, 0xf4,
	0x9f, 0xa6, 0x74, 0xfb, 0x61, 0x0f, 0x9a, 0x41, 0xc6, 0x2d, 0x86, 0xb9, 0xf5, 0xbb, 0x6e, 0x2b,
	0x0e, 0x00, 0x19, 0x40, 0x6f, 0x43, 0x99, 0xf9, 0x0c, 0x18, 0x0f, 0xee, 0x72, 0xcc, 0xd1, 0x36,
	0xad, 0xe9, 0x77, 0x0a, 0x7c, 0xc6, 0x7f, 0x35, 0x68, 0xf1, 0xa8, 0xa5, 0xc8, 0x6e, 0x3e, 0xed,
	0x95, 0xbd, 0x83, 0x4e, 0x05, 0x33, 0xa2, 0x5e, 0x43, 0x3b, 0xe5, 0x81, 0x16, 0x59, 0x90, 0x30,
	0xa5, 0xed, 0x86, 0x69, 0xf9, 0xad, 0x94, 0x2f, 0x45, 0xf6, 0x91, 0x29, 0x3d, 0x79, 0xff, 0xfb,
	0xbb, 0x98, 0xe9, 0x75, 0xbe, 0x1a, 0x86, 0x22, 0x1d, 0x65, 0xf6, 0x57, 0xe6, 0xa8, 0x37, 0x42,
	0xde, 0x8e, 0x62, 0x61, 0xf6, 0xc5, 0xc8, 0x6e, 0xff, 0xd1, 0x61, 0x27, 0xad, 0x4e, 0x2d, 0xf2,
	0xed, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x7d, 0xd1, 0xb8, 0x22, 0x06, 0x00, 0x00,
}
