log-level: info
log-file: # e.g: logs.json
quiet: false
temp-dir: "/tmp/walletnode"
work-dir:
rq-files-dir: 

node:
  api:
    hostname: "localhost"
    port: 8080
    swagger: true 
  burn_address: tPce2T47TFPcHPj3sKiKdFLhQpmzJ1tkzjr 

raptorq:
  host: "locahost"
  port: 50051
  