pastel-api:
  hostname: "127.0.0.1"
  port: 12172
  username: "rt"
  password: "rt"

node:
  api:
    hostname: "localhost"
    port: 8080
  burn_address: tPce2T47TFPcHPj3sKiKdFLhQpmzJ1tkzjr 

raptorq:
  hostname: "locahost"
  port: 50051
