pastel-api:
  hostname: "127.0.0.1"
  port: 12170
  username: "rt"
  password: "rt"

node:
  api:
    hostname: "localhost"
    port: 8080
  reg_art_tx_min_confirmation: 10
  # Timeout waiting for 
  reg_art_tx_confirmation_timeout: 30
  burn_address: tPce2T47TFPcHPj3sKiKdFLhQpmzJ1tkzjr 

raptorq:
  hostname: "locahost"
  port: 50051
