pastel-api:
  hostname: "127.0.0.1"
  port: 12170
  username: "rt"
  password: "rt"

node:
  api:
    hostname: "localhost"
    port: 8080
  reg_art_tx_min_confirmations: 10
  # Timeout waiting for 
  reg_art_tx_timeout: 26
  reg_act_tx_min_confirmations: 5 
  # Timeout waiting for 
  reg_act_tx_timeout: 13
  burn_address: tPce2T47TFPcHPj3sKiKdFLhQpmzJ1tkzjr 
  number_super_nodes: 3
  minimal_node_confirm_success: 2

raptorq:
  hostname: "locahost"
  port: 50051
