log-level:
log-file:
quiet: false
temp-dir:
work-dir:
rq-files-dir: 

node:
  api:
    hostname: "localhost"
    port: 8080
    swagger: true 
  burn_address: tPce2T47TFPcHPj3sKiKdFLhQpmzJ1tkzjr 

raptorq:
  host: "localhost"
  port: 50051
  