log-level:
log-file:
quiet: false
temp-dir:
work-dir:
rq-files-dir: 

node:
  api:
    hostname: "localhost"
    port: 8080
    swagger: true 
  burn_address: "PtpasteLBurnAddressXXXXXXXXXXbJ5ndd" 

raptorq:
  host: "localhost"
  port: 50051
