log-level: info
log-file: # e.g: logs.json
quiet: false
temp-dir: "/tmp/walletnode"
work-dir:
rq-files-dir: /home/matee/.pastel/rq

node:
  api:
    hostname: "localhost"
    port: 8080
    swagger: true 
  reg_art_tx_min_confirmations: 10
  # Timeout in minutes 
  reg_art_tx_timeout: 26
  reg_act_tx_min_confirmations: 5 
  # Timeout in minutes
  reg_act_tx_timeout: 13
  burn_address: "PtpasteLBurnAddressXXXXXXXXXXbJ5ndd" 
  # userdata_process
  minimal_node_confirm_success: 2

raptorq:
  host: "locahost"
  port: 50051

p2p:
  listen_address: "0.0.0.0"
  port: 6000
  data_dir: "p2p-localnet-6000"
  bootstrap_ip: #string
  bootstap_port: #int
  