pastel-api:
  port: 19932

node:
  api:
    hostname: "localhost"
    port: 8080
  burn_address: "tPpasteLBurnAddressXXXXXXXXXXX3wy7u"
  userdata_process:
    number_super_nodes: 3
    minimal_node_confirm_success: 2
