log-config:
  log-level: info
  log-file: /home/mrrobot/.pastel/bridge.log
  log-compress: true
  log-max-size-mb: 100
  log-max-age-days: 3
  log-max-backups: 10
quiet: false
temp-dir: /home/mrrobot/.pastel/tmp
work-dir: /home/mrrobot/.pastel

download:
  pastelid: jXXbtngohP4dqsvL64zdnpDjmDRRrDEaDJbjmwSVptHfaXZ3wEZWbvWSNUsNZC25GYd4n4nagqEFsvdP6odNDZ
  passphrase: passphrase
  connection_refresh_timeout: 300
  connections: 10

server:
  listen_addresses: 127.0.0.1
  port: 60061

