// Code generated by protoc-gen-go. DO NOT EDIT.
// source: self_healing.proto

package supernode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SelfHealingDataMessageType int32

const (
	SelfHealingData_MessageType_UNKNOWN                           SelfHealingDataMessageType = 0
	SelfHealingData_MessageType_SELF_HEALING_ISSUANCE_MESSAGE     SelfHealingDataMessageType = 1
	SelfHealingData_MessageType_SELF_HEALING_RESPONSE_MESSAGE     SelfHealingDataMessageType = 2
	SelfHealingData_MessageType_SELF_HEALING_VERIFICATION_MESSAGE SelfHealingDataMessageType = 3
)

var SelfHealingDataMessageType_name = map[int32]string{
	0: "MessageType_UNKNOWN",
	1: "MessageType_SELF_HEALING_ISSUANCE_MESSAGE",
	2: "MessageType_SELF_HEALING_RESPONSE_MESSAGE",
	3: "MessageType_SELF_HEALING_VERIFICATION_MESSAGE",
}

var SelfHealingDataMessageType_value = map[string]int32{
	"MessageType_UNKNOWN":                           0,
	"MessageType_SELF_HEALING_ISSUANCE_MESSAGE":     1,
	"MessageType_SELF_HEALING_RESPONSE_MESSAGE":     2,
	"MessageType_SELF_HEALING_VERIFICATION_MESSAGE": 3,
}

func (x SelfHealingDataMessageType) String() string {
	return proto.EnumName(SelfHealingDataMessageType_name, int32(x))
}

func (SelfHealingDataMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{2, 0}
}

type SelfHealingDataStatus int32

const (
	SelfHealingData_Status_UNKNOWN                   SelfHealingDataStatus = 0
	SelfHealingData_Status_PENDING                   SelfHealingDataStatus = 1
	SelfHealingData_Status_RESPONDED                 SelfHealingDataStatus = 2
	SelfHealingData_Status_SUCCEEDED                 SelfHealingDataStatus = 3
	SelfHealingData_Status_FAILED_TIMEOUT            SelfHealingDataStatus = 4
	SelfHealingData_Status_FAILED_INCORRECT_RESPONSE SelfHealingDataStatus = 5
)

var SelfHealingDataStatus_name = map[int32]string{
	0: "Status_UNKNOWN",
	1: "Status_PENDING",
	2: "Status_RESPONDED",
	3: "Status_SUCCEEDED",
	4: "Status_FAILED_TIMEOUT",
	5: "Status_FAILED_INCORRECT_RESPONSE",
}

var SelfHealingDataStatus_value = map[string]int32{
	"Status_UNKNOWN":                   0,
	"Status_PENDING":                   1,
	"Status_RESPONDED":                 2,
	"Status_SUCCEEDED":                 3,
	"Status_FAILED_TIMEOUT":            4,
	"Status_FAILED_INCORRECT_RESPONSE": 5,
}

func (x SelfHealingDataStatus) String() string {
	return proto.EnumName(SelfHealingDataStatus_name, int32(x))
}

func (SelfHealingDataStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{2, 1}
}

type SelfHealingMessageMessageType int32

const (
	SelfHealingMessage_MessageType_UNKNOWN                        SelfHealingMessageMessageType = 0
	SelfHealingMessage_MessageType_SELF_HEALING_CHALLENGE_MESSAGE SelfHealingMessageMessageType = 1
	SelfHealingMessage_MessageType_SELF_HEALING_RESPONSE_MESSAGE  SelfHealingMessageMessageType = 2
)

var SelfHealingMessageMessageType_name = map[int32]string{
	0: "MessageType_UNKNOWN",
	1: "MessageType_SELF_HEALING_CHALLENGE_MESSAGE",
	2: "MessageType_SELF_HEALING_RESPONSE_MESSAGE",
}

var SelfHealingMessageMessageType_value = map[string]int32{
	"MessageType_UNKNOWN":                        0,
	"MessageType_SELF_HEALING_CHALLENGE_MESSAGE": 1,
	"MessageType_SELF_HEALING_RESPONSE_MESSAGE":  2,
}

func (x SelfHealingMessageMessageType) String() string {
	return proto.EnumName(SelfHealingMessageMessageType_name, int32(x))
}

func (SelfHealingMessageMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{7, 0}
}

type PingRequest struct {
	SenderId             string   `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

type PingResponse struct {
	SenderId             string   `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId           string   `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	IsOnline             bool     `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	RespondedAt          string   `protobuf:"bytes,4,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *PingResponse) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *PingResponse) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *PingResponse) GetRespondedAt() string {
	if m != nil {
		return m.RespondedAt
	}
	return ""
}

type SelfHealingData struct {
	MessageId                   string                        `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType                 SelfHealingDataMessageType    `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=supernode.SelfHealingDataMessageType" json:"message_type,omitempty"`
	ChallengeStatus             SelfHealingDataStatus         `protobuf:"varint,3,opt,name=challenge_status,json=challengeStatus,proto3,enum=supernode.SelfHealingDataStatus" json:"challenge_status,omitempty"`
	MerklerootWhenChallengeSent string                        `protobuf:"bytes,4,opt,name=merkleroot_when_challenge_sent,json=merklerootWhenChallengeSent,proto3" json:"merkleroot_when_challenge_sent,omitempty"`
	ChallengingMasternodeId     string                        `protobuf:"bytes,5,opt,name=challenging_masternode_id,json=challengingMasternodeId,proto3" json:"challenging_masternode_id,omitempty"`
	RespondingMasternodeId      string                        `protobuf:"bytes,6,opt,name=responding_masternode_id,json=respondingMasternodeId,proto3" json:"responding_masternode_id,omitempty"`
	ReconstructedFileHash       []byte                        `protobuf:"bytes,7,opt,name=reconstructed_file_hash,json=reconstructedFileHash,proto3" json:"reconstructed_file_hash,omitempty"`
	ChallengeFile               *SelfHealingDataChallengeFile `protobuf:"bytes,8,opt,name=challenge_file,json=challengeFile,proto3" json:"challenge_file,omitempty"`
	ChallengeId                 string                        `protobuf:"bytes,9,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	RegTicketId                 string                        `protobuf:"bytes,10,opt,name=reg_ticket_id,json=regTicketId,proto3" json:"reg_ticket_id,omitempty"`
	ActionTicketId              string                        `protobuf:"bytes,11,opt,name=action_ticket_id,json=actionTicketId,proto3" json:"action_ticket_id,omitempty"`
	IsSenseTicket               bool                          `protobuf:"varint,12,opt,name=is_sense_ticket,json=isSenseTicket,proto3" json:"is_sense_ticket,omitempty"`
	SenseFileIds                []string                      `protobuf:"bytes,13,rep,name=senseFileIds,proto3" json:"senseFileIds,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                      `json:"-"`
	XXX_unrecognized            []byte                        `json:"-"`
	XXX_sizecache               int32                         `json:"-"`
}

func (m *SelfHealingData) Reset()         { *m = SelfHealingData{} }
func (m *SelfHealingData) String() string { return proto.CompactTextString(m) }
func (*SelfHealingData) ProtoMessage()    {}
func (*SelfHealingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{2}
}

func (m *SelfHealingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfHealingData.Unmarshal(m, b)
}
func (m *SelfHealingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfHealingData.Marshal(b, m, deterministic)
}
func (m *SelfHealingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfHealingData.Merge(m, src)
}
func (m *SelfHealingData) XXX_Size() int {
	return xxx_messageInfo_SelfHealingData.Size(m)
}
func (m *SelfHealingData) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfHealingData.DiscardUnknown(m)
}

var xxx_messageInfo_SelfHealingData proto.InternalMessageInfo

func (m *SelfHealingData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SelfHealingData) GetMessageType() SelfHealingDataMessageType {
	if m != nil {
		return m.MessageType
	}
	return SelfHealingData_MessageType_UNKNOWN
}

func (m *SelfHealingData) GetChallengeStatus() SelfHealingDataStatus {
	if m != nil {
		return m.ChallengeStatus
	}
	return SelfHealingData_Status_UNKNOWN
}

func (m *SelfHealingData) GetMerklerootWhenChallengeSent() string {
	if m != nil {
		return m.MerklerootWhenChallengeSent
	}
	return ""
}

func (m *SelfHealingData) GetChallengingMasternodeId() string {
	if m != nil {
		return m.ChallengingMasternodeId
	}
	return ""
}

func (m *SelfHealingData) GetRespondingMasternodeId() string {
	if m != nil {
		return m.RespondingMasternodeId
	}
	return ""
}

func (m *SelfHealingData) GetReconstructedFileHash() []byte {
	if m != nil {
		return m.ReconstructedFileHash
	}
	return nil
}

func (m *SelfHealingData) GetChallengeFile() *SelfHealingDataChallengeFile {
	if m != nil {
		return m.ChallengeFile
	}
	return nil
}

func (m *SelfHealingData) GetChallengeId() string {
	if m != nil {
		return m.ChallengeId
	}
	return ""
}

func (m *SelfHealingData) GetRegTicketId() string {
	if m != nil {
		return m.RegTicketId
	}
	return ""
}

func (m *SelfHealingData) GetActionTicketId() string {
	if m != nil {
		return m.ActionTicketId
	}
	return ""
}

func (m *SelfHealingData) GetIsSenseTicket() bool {
	if m != nil {
		return m.IsSenseTicket
	}
	return false
}

func (m *SelfHealingData) GetSenseFileIds() []string {
	if m != nil {
		return m.SenseFileIds
	}
	return nil
}

type SelfHealingDataChallengeFile struct {
	FileHashToChallenge  string   `protobuf:"bytes,1,opt,name=file_hash_to_challenge,json=fileHashToChallenge,proto3" json:"file_hash_to_challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfHealingDataChallengeFile) Reset()         { *m = SelfHealingDataChallengeFile{} }
func (m *SelfHealingDataChallengeFile) String() string { return proto.CompactTextString(m) }
func (*SelfHealingDataChallengeFile) ProtoMessage()    {}
func (*SelfHealingDataChallengeFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{2, 0}
}

func (m *SelfHealingDataChallengeFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfHealingDataChallengeFile.Unmarshal(m, b)
}
func (m *SelfHealingDataChallengeFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfHealingDataChallengeFile.Marshal(b, m, deterministic)
}
func (m *SelfHealingDataChallengeFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfHealingDataChallengeFile.Merge(m, src)
}
func (m *SelfHealingDataChallengeFile) XXX_Size() int {
	return xxx_messageInfo_SelfHealingDataChallengeFile.Size(m)
}
func (m *SelfHealingDataChallengeFile) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfHealingDataChallengeFile.DiscardUnknown(m)
}

var xxx_messageInfo_SelfHealingDataChallengeFile proto.InternalMessageInfo

func (m *SelfHealingDataChallengeFile) GetFileHashToChallenge() string {
	if m != nil {
		return m.FileHashToChallenge
	}
	return ""
}

type ProcessSelfHealingChallengeRequest struct {
	Data                 *SelfHealingMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProcessSelfHealingChallengeRequest) Reset()         { *m = ProcessSelfHealingChallengeRequest{} }
func (m *ProcessSelfHealingChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessSelfHealingChallengeRequest) ProtoMessage()    {}
func (*ProcessSelfHealingChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{3}
}

func (m *ProcessSelfHealingChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSelfHealingChallengeRequest.Unmarshal(m, b)
}
func (m *ProcessSelfHealingChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSelfHealingChallengeRequest.Marshal(b, m, deterministic)
}
func (m *ProcessSelfHealingChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSelfHealingChallengeRequest.Merge(m, src)
}
func (m *ProcessSelfHealingChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessSelfHealingChallengeRequest.Size(m)
}
func (m *ProcessSelfHealingChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSelfHealingChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSelfHealingChallengeRequest proto.InternalMessageInfo

func (m *ProcessSelfHealingChallengeRequest) GetData() *SelfHealingMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProcessSelfHealingChallengeReply struct {
	Data                 *SelfHealingMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProcessSelfHealingChallengeReply) Reset()         { *m = ProcessSelfHealingChallengeReply{} }
func (m *ProcessSelfHealingChallengeReply) String() string { return proto.CompactTextString(m) }
func (*ProcessSelfHealingChallengeReply) ProtoMessage()    {}
func (*ProcessSelfHealingChallengeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{4}
}

func (m *ProcessSelfHealingChallengeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSelfHealingChallengeReply.Unmarshal(m, b)
}
func (m *ProcessSelfHealingChallengeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSelfHealingChallengeReply.Marshal(b, m, deterministic)
}
func (m *ProcessSelfHealingChallengeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSelfHealingChallengeReply.Merge(m, src)
}
func (m *ProcessSelfHealingChallengeReply) XXX_Size() int {
	return xxx_messageInfo_ProcessSelfHealingChallengeReply.Size(m)
}
func (m *ProcessSelfHealingChallengeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSelfHealingChallengeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSelfHealingChallengeReply proto.InternalMessageInfo

func (m *ProcessSelfHealingChallengeReply) GetData() *SelfHealingMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifySelfHealingChallengeRequest struct {
	Data                 *SelfHealingMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VerifySelfHealingChallengeRequest) Reset()         { *m = VerifySelfHealingChallengeRequest{} }
func (m *VerifySelfHealingChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifySelfHealingChallengeRequest) ProtoMessage()    {}
func (*VerifySelfHealingChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{5}
}

func (m *VerifySelfHealingChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySelfHealingChallengeRequest.Unmarshal(m, b)
}
func (m *VerifySelfHealingChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySelfHealingChallengeRequest.Marshal(b, m, deterministic)
}
func (m *VerifySelfHealingChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySelfHealingChallengeRequest.Merge(m, src)
}
func (m *VerifySelfHealingChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifySelfHealingChallengeRequest.Size(m)
}
func (m *VerifySelfHealingChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySelfHealingChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySelfHealingChallengeRequest proto.InternalMessageInfo

func (m *VerifySelfHealingChallengeRequest) GetData() *SelfHealingMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifySelfHealingChallengeReply struct {
	Data                 *SelfHealingMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VerifySelfHealingChallengeReply) Reset()         { *m = VerifySelfHealingChallengeReply{} }
func (m *VerifySelfHealingChallengeReply) String() string { return proto.CompactTextString(m) }
func (*VerifySelfHealingChallengeReply) ProtoMessage()    {}
func (*VerifySelfHealingChallengeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{6}
}

func (m *VerifySelfHealingChallengeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySelfHealingChallengeReply.Unmarshal(m, b)
}
func (m *VerifySelfHealingChallengeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySelfHealingChallengeReply.Marshal(b, m, deterministic)
}
func (m *VerifySelfHealingChallengeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySelfHealingChallengeReply.Merge(m, src)
}
func (m *VerifySelfHealingChallengeReply) XXX_Size() int {
	return xxx_messageInfo_VerifySelfHealingChallengeReply.Size(m)
}
func (m *VerifySelfHealingChallengeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySelfHealingChallengeReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySelfHealingChallengeReply proto.InternalMessageInfo

func (m *VerifySelfHealingChallengeReply) GetData() *SelfHealingMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type SelfHealingMessage struct {
	MessageType          SelfHealingMessageMessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=supernode.SelfHealingMessageMessageType" json:"message_type,omitempty"`
	ChallengeId          string                        `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Data                 []byte                        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	SenderId             string                        `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderSignature      []byte                        `protobuf:"bytes,5,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SelfHealingMessage) Reset()         { *m = SelfHealingMessage{} }
func (m *SelfHealingMessage) String() string { return proto.CompactTextString(m) }
func (*SelfHealingMessage) ProtoMessage()    {}
func (*SelfHealingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6b4541a7de850f, []int{7}
}

func (m *SelfHealingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfHealingMessage.Unmarshal(m, b)
}
func (m *SelfHealingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfHealingMessage.Marshal(b, m, deterministic)
}
func (m *SelfHealingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfHealingMessage.Merge(m, src)
}
func (m *SelfHealingMessage) XXX_Size() int {
	return xxx_messageInfo_SelfHealingMessage.Size(m)
}
func (m *SelfHealingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfHealingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SelfHealingMessage proto.InternalMessageInfo

func (m *SelfHealingMessage) GetMessageType() SelfHealingMessageMessageType {
	if m != nil {
		return m.MessageType
	}
	return SelfHealingMessage_MessageType_UNKNOWN
}

func (m *SelfHealingMessage) GetChallengeId() string {
	if m != nil {
		return m.ChallengeId
	}
	return ""
}

func (m *SelfHealingMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SelfHealingMessage) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *SelfHealingMessage) GetSenderSignature() []byte {
	if m != nil {
		return m.SenderSignature
	}
	return nil
}

func init() {
	proto.RegisterEnum("supernode.SelfHealingDataMessageType", SelfHealingDataMessageType_name, SelfHealingDataMessageType_value)
	proto.RegisterEnum("supernode.SelfHealingDataStatus", SelfHealingDataStatus_name, SelfHealingDataStatus_value)
	proto.RegisterEnum("supernode.SelfHealingMessageMessageType", SelfHealingMessageMessageType_name, SelfHealingMessageMessageType_value)
	proto.RegisterType((*PingRequest)(nil), "supernode.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "supernode.PingResponse")
	proto.RegisterType((*SelfHealingData)(nil), "supernode.SelfHealingData")
	proto.RegisterType((*SelfHealingDataChallengeFile)(nil), "supernode.SelfHealingData.challengeFile")
	proto.RegisterType((*ProcessSelfHealingChallengeRequest)(nil), "supernode.ProcessSelfHealingChallengeRequest")
	proto.RegisterType((*ProcessSelfHealingChallengeReply)(nil), "supernode.ProcessSelfHealingChallengeReply")
	proto.RegisterType((*VerifySelfHealingChallengeRequest)(nil), "supernode.VerifySelfHealingChallengeRequest")
	proto.RegisterType((*VerifySelfHealingChallengeReply)(nil), "supernode.VerifySelfHealingChallengeReply")
	proto.RegisterType((*SelfHealingMessage)(nil), "supernode.SelfHealingMessage")
}

func init() { proto.RegisterFile("self_healing.proto", fileDescriptor_ae6b4541a7de850f) }

var fileDescriptor_ae6b4541a7de850f = []byte{
	// 969 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xae, 0x49, 0x36, 0x1b, 0x0e, 0x04, 0xac, 0xd9, 0x6e, 0x42, 0x88, 0xb6, 0x4b, 0xac, 0x6a,
	0x45, 0xd2, 0x86, 0x74, 0x59, 0xa9, 0x7f, 0x7b, 0x45, 0xc1, 0x49, 0xac, 0x12, 0x13, 0xd9, 0x90,
	0x48, 0xbd, 0xb1, 0xbc, 0x78, 0x30, 0xa3, 0x98, 0x31, 0xf5, 0x0c, 0xbb, 0xe2, 0x01, 0x7a, 0xd7,
	0x57, 0xe8, 0x73, 0xf4, 0x99, 0xda, 0x67, 0xe8, 0x45, 0xe5, 0xb1, 0x31, 0x36, 0xd9, 0xb0, 0x51,
	0xb4, 0x77, 0xf8, 0x3b, 0xdf, 0xf9, 0x38, 0x73, 0xfc, 0x9d, 0xe3, 0x01, 0xc4, 0xb0, 0x37, 0xb2,
	0xc6, 0xd8, 0xf6, 0x08, 0x75, 0x1b, 0xd3, 0xc0, 0xe7, 0x3e, 0xca, 0xb3, 0xd9, 0x14, 0x07, 0xd4,
	0x77, 0x70, 0xb5, 0x3c, 0xf4, 0x27, 0x13, 0x9f, 0x5a, 0x8c, 0x46, 0x31, 0xe5, 0x18, 0x0a, 0x57,
	0x84, 0xba, 0x06, 0xfe, 0x7d, 0x86, 0x19, 0x47, 0x07, 0x90, 0x67, 0x98, 0x3a, 0x38, 0xb0, 0x88,
	0x53, 0x91, 0x6a, 0x52, 0x3d, 0x6f, 0x6c, 0x47, 0x80, 0xe6, 0x28, 0x7f, 0x4a, 0x50, 0x8c, 0xc8,
	0x6c, 0xea, 0x53, 0x86, 0xd7, 0xb2, 0xd1, 0x4b, 0x28, 0x04, 0x78, 0x88, 0xc9, 0xfb, 0x28, 0x9c,
	0x13, 0x61, 0x58, 0x40, 0x9a, 0x13, 0x66, 0x13, 0x66, 0xf9, 0xd4, 0x23, 0x14, 0x57, 0x36, 0x6a,
	0x52, 0x7d, 0xdb, 0xd8, 0x26, 0xac, 0x27, 0x9e, 0xd1, 0x21, 0x14, 0x03, 0xf1, 0x37, 0x0e, 0x76,
	0x2c, 0x9b, 0x57, 0x36, 0x45, 0x7a, 0x21, 0xc1, 0x5a, 0x5c, 0xf9, 0x77, 0x1b, 0xca, 0x26, 0xf6,
	0x46, 0x17, 0xd1, 0x61, 0x3b, 0x36, 0xb7, 0xd1, 0x0b, 0x80, 0x09, 0x66, 0xcc, 0x76, 0xf1, 0xb2,
	0xa4, 0x7c, 0x8c, 0x68, 0x0e, 0xd2, 0xa0, 0xb8, 0x08, 0xf3, 0xf9, 0x14, 0x8b, 0xa2, 0x4a, 0xcd,
	0x57, 0x8d, 0xa4, 0x41, 0x8d, 0x15, 0xc1, 0x46, 0x4c, 0xef, 0xcf, 0xa7, 0xd8, 0x28, 0xa4, 0x1e,
	0x50, 0x17, 0xe4, 0xe1, 0xd8, 0xf6, 0x3c, 0x4c, 0x5d, 0x6c, 0x31, 0x6e, 0xf3, 0x19, 0x13, 0x87,
	0x28, 0x35, 0x0f, 0xd7, 0xc8, 0x45, 0x44, 0xa3, 0x9c, 0xa4, 0x9a, 0x02, 0x40, 0x6d, 0xf8, 0x6a,
	0x82, 0x83, 0x5b, 0x0f, 0x07, 0xbe, 0xcf, 0xad, 0x0f, 0x63, 0x4c, 0xad, 0x94, 0x3a, 0xa6, 0x8b,
	0x06, 0x1c, 0x2c, 0x59, 0x37, 0x63, 0x4c, 0xdb, 0x89, 0x0c, 0xa6, 0x1c, 0xfd, 0x0c, 0xfb, 0x8b,
	0x24, 0x42, 0x5d, 0x6b, 0x62, 0x33, 0x1e, 0x95, 0x11, 0xf6, 0xe2, 0x89, 0xc8, 0xdf, 0x4b, 0x11,
	0x2e, 0x93, 0xb8, 0xe6, 0xa0, 0x1f, 0xa1, 0x12, 0xf7, 0xf6, 0x6e, 0xea, 0x96, 0x48, 0xdd, 0x5d,
	0xc6, 0x33, 0x99, 0xdf, 0xc3, 0x5e, 0x80, 0x87, 0x3e, 0x65, 0x3c, 0x98, 0x0d, 0x39, 0x76, 0xac,
	0x11, 0xf1, 0xb0, 0x35, 0xb6, 0xd9, 0xb8, 0xf2, 0xb4, 0x26, 0xd5, 0x8b, 0xc6, 0xf3, 0x4c, 0xf8,
	0x8c, 0x78, 0xf8, 0xc2, 0x66, 0x63, 0xd4, 0x83, 0xd2, 0xf2, 0x88, 0x61, 0x4e, 0x65, 0xbb, 0x26,
	0xd5, 0x0b, 0xcd, 0xfa, 0x9a, 0xf6, 0x25, 0x09, 0xa1, 0x8a, 0xb1, 0x93, 0x79, 0x0c, 0x2d, 0xb3,
	0x14, 0x24, 0x4e, 0x25, 0x1f, 0x59, 0x26, 0xc1, 0x34, 0x07, 0x29, 0xb0, 0x13, 0x60, 0xd7, 0xe2,
	0x64, 0x78, 0x8b, 0x79, 0xc8, 0x81, 0x85, 0xad, 0xdc, 0xbe, 0xc0, 0x34, 0x07, 0xd5, 0x41, 0xb6,
	0x87, 0x9c, 0xf8, 0x34, 0x45, 0x2b, 0x08, 0x5a, 0x29, 0xc2, 0x13, 0xe6, 0x2b, 0x28, 0x13, 0x16,
	0xbe, 0x1d, 0x86, 0x63, 0x6e, 0xa5, 0x28, 0x6c, 0xbc, 0x43, 0x98, 0x19, 0xa2, 0x11, 0x13, 0x29,
	0x50, 0x14, 0xa4, 0xb0, 0x4a, 0xcd, 0x61, 0x95, 0x9d, 0xda, 0x46, 0x3d, 0x6f, 0x64, 0xb0, 0x6a,
	0x07, 0x56, 0x4e, 0xf3, 0x06, 0x76, 0x93, 0x46, 0x5a, 0xdc, 0x5f, 0xda, 0x21, 0x76, 0xf5, 0xb3,
	0x51, 0xdc, 0xc8, 0xbe, 0x9f, 0xb8, 0x40, 0xf9, 0x5b, 0x82, 0x8c, 0x49, 0xf7, 0xe0, 0xd9, 0xe5,
	0xf2, 0xd1, 0x1a, 0xe8, 0xbf, 0xea, 0xbd, 0x1b, 0x5d, 0xfe, 0x02, 0x9d, 0xc0, 0x51, 0x3a, 0x60,
	0xaa, 0xdd, 0x33, 0xeb, 0x42, 0x6d, 0x75, 0x35, 0xfd, 0xdc, 0xd2, 0x4c, 0x73, 0xd0, 0xd2, 0xdb,
	0xaa, 0x75, 0xa9, 0x9a, 0x66, 0xeb, 0x5c, 0x95, 0xa5, 0xb5, 0x74, 0x43, 0x35, 0xaf, 0x7a, 0xba,
	0xb9, 0xa4, 0xe7, 0xd0, 0x6b, 0x38, 0xb9, 0x97, 0x7e, 0xad, 0x1a, 0xda, 0x99, 0xd6, 0x6e, 0xf5,
	0xb5, 0x9e, 0x9e, 0xa4, 0x6c, 0x28, 0x7f, 0x49, 0xb0, 0x15, 0x0d, 0x07, 0x42, 0x50, 0x8a, 0xa6,
	0x22, 0x55, 0xef, 0x12, 0xbb, 0x52, 0xf5, 0x8e, 0xa6, 0x9f, 0xcb, 0x12, 0xfa, 0x12, 0xe4, 0x18,
	0x8b, 0x4a, 0xe8, 0xa8, 0x1d, 0x39, 0x97, 0x42, 0xcd, 0x41, 0xbb, 0xad, 0xaa, 0x21, 0xba, 0x81,
	0xf6, 0xe1, 0x79, 0x8c, 0x9e, 0xb5, 0xb4, 0xae, 0xda, 0xb1, 0xfa, 0xda, 0xa5, 0xda, 0x1b, 0xf4,
	0xe5, 0x4d, 0xf4, 0x35, 0xd4, 0xb2, 0x21, 0x4d, 0x6f, 0xf7, 0x0c, 0x43, 0x6d, 0xf7, 0x93, 0xa3,
	0xc9, 0x4f, 0x94, 0x1b, 0x50, 0xae, 0x02, 0x7f, 0x88, 0x19, 0x4b, 0x79, 0x32, 0x69, 0xfc, 0x62,
	0x7d, 0xbe, 0x86, 0x4d, 0xc7, 0xe6, 0xb6, 0x78, 0x45, 0x85, 0xe6, 0x8b, 0x8f, 0x3b, 0x39, 0x6e,
	0x8d, 0x21, 0xa8, 0xca, 0x00, 0x6a, 0x6b, 0x85, 0xa7, 0xde, 0xfc, 0x31, 0xb2, 0xd7, 0x70, 0x78,
	0x8d, 0x03, 0x32, 0x9a, 0x7f, 0xe6, 0x72, 0xfb, 0xf0, 0x72, 0x9d, 0xee, 0x23, 0xab, 0xfd, 0x27,
	0x07, 0xe8, 0x6e, 0x10, 0x75, 0x57, 0xd6, 0xb5, 0x24, 0xf6, 0xeb, 0xd1, 0x5a, 0xc5, 0xfb, 0x37,
	0xf6, 0xea, 0x7e, 0xc8, 0xdd, 0xdd, 0x0f, 0x28, 0x2e, 0x7d, 0x43, 0x2c, 0x2e, 0xf1, 0x3b, 0xfb,
	0x91, 0xdb, 0x5c, 0xf9, 0xc8, 0x1d, 0x81, 0x1c, 0x07, 0x19, 0x71, 0xa9, 0xcd, 0x67, 0x01, 0x16,
	0x9b, 0xb6, 0x68, 0x94, 0x23, 0xdc, 0x5c, 0xc0, 0xca, 0x1f, 0x0f, 0x9d, 0xcd, 0x06, 0x1c, 0xdf,
	0x3b, 0x3d, 0xed, 0x8b, 0x56, 0xb7, 0xab, 0xea, 0xe7, 0x8f, 0x1f, 0xce, 0xe6, 0x7f, 0x39, 0x28,
	0xa4, 0xda, 0x86, 0x5a, 0xf0, 0xd4, 0xc4, 0x8c, 0x11, 0x9f, 0xa2, 0xfd, 0x4c, 0x67, 0x05, 0x16,
	0x5b, 0xa5, 0xba, 0xf7, 0xb1, 0xd0, 0xd4, 0x9b, 0xd7, 0xa5, 0xef, 0x24, 0xf4, 0x03, 0x6c, 0x86,
	0xf7, 0x02, 0xb4, 0x9b, 0x22, 0xa5, 0x6e, 0x15, 0x99, 0xe4, 0xcc, 0x05, 0x62, 0x0e, 0x07, 0x6b,
	0xcc, 0x8f, 0x4e, 0xd2, 0x79, 0x9f, 0x9c, 0xbe, 0xea, 0x37, 0x0f, 0xa5, 0x87, 0x2e, 0x7d, 0x0f,
	0xd5, 0xfb, 0x8d, 0x8c, 0xbe, 0x4d, 0x49, 0x7d, 0x72, 0x8e, 0xaa, 0xc7, 0x0f, 0x64, 0x4f, 0xbd,
	0xf9, 0x2f, 0x6f, 0x7f, 0xfb, 0xc9, 0x25, 0x7c, 0x3c, 0x7b, 0xd7, 0x18, 0xfa, 0x93, 0xd3, 0x69,
	0xf8, 0x25, 0xf5, 0x28, 0xe6, 0x1f, 0xfc, 0xe0, 0xf6, 0xd4, 0xf5, 0x43, 0x89, 0x53, 0x71, 0x33,
	0x3b, 0x4d, 0x24, 0xdf, 0x26, 0xbf, 0xde, 0x6d, 0x89, 0xd0, 0x9b, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xac, 0x1f, 0x36, 0xa5, 0xe6, 0x09, 0x00, 0x00,
}
