// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage_challenge.proto

package supernode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageChallengeDataMessageType int32

const (
	StorageChallengeData_MessageType_UNKNOWN                                StorageChallengeDataMessageType = 0
	StorageChallengeData_MessageType_STORAGE_CHALLENGE_ISSUANCE_MESSAGE     StorageChallengeDataMessageType = 1
	StorageChallengeData_MessageType_STORAGE_CHALLENGE_RESPONSE_MESSAGE     StorageChallengeDataMessageType = 2
	StorageChallengeData_MessageType_STORAGE_CHALLENGE_VERIFICATION_MESSAGE StorageChallengeDataMessageType = 3
)

var StorageChallengeDataMessageType_name = map[int32]string{
	0: "MessageType_UNKNOWN",
	1: "MessageType_STORAGE_CHALLENGE_ISSUANCE_MESSAGE",
	2: "MessageType_STORAGE_CHALLENGE_RESPONSE_MESSAGE",
	3: "MessageType_STORAGE_CHALLENGE_VERIFICATION_MESSAGE",
}

var StorageChallengeDataMessageType_value = map[string]int32{
	"MessageType_UNKNOWN":                                0,
	"MessageType_STORAGE_CHALLENGE_ISSUANCE_MESSAGE":     1,
	"MessageType_STORAGE_CHALLENGE_RESPONSE_MESSAGE":     2,
	"MessageType_STORAGE_CHALLENGE_VERIFICATION_MESSAGE": 3,
}

func (x StorageChallengeDataMessageType) String() string {
	return proto.EnumName(StorageChallengeDataMessageType_name, int32(x))
}

func (StorageChallengeDataMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{0, 0}
}

type StorageChallengeDataStatus int32

const (
	StorageChallengeData_Status_UNKNOWN                   StorageChallengeDataStatus = 0
	StorageChallengeData_Status_PENDING                   StorageChallengeDataStatus = 1
	StorageChallengeData_Status_RESPONDED                 StorageChallengeDataStatus = 2
	StorageChallengeData_Status_SUCCEEDED                 StorageChallengeDataStatus = 3
	StorageChallengeData_Status_FAILED_TIMEOUT            StorageChallengeDataStatus = 4
	StorageChallengeData_Status_FAILED_INCORRECT_RESPONSE StorageChallengeDataStatus = 5
)

var StorageChallengeDataStatus_name = map[int32]string{
	0: "Status_UNKNOWN",
	1: "Status_PENDING",
	2: "Status_RESPONDED",
	3: "Status_SUCCEEDED",
	4: "Status_FAILED_TIMEOUT",
	5: "Status_FAILED_INCORRECT_RESPONSE",
}

var StorageChallengeDataStatus_value = map[string]int32{
	"Status_UNKNOWN":                   0,
	"Status_PENDING":                   1,
	"Status_RESPONDED":                 2,
	"Status_SUCCEEDED":                 3,
	"Status_FAILED_TIMEOUT":            4,
	"Status_FAILED_INCORRECT_RESPONSE": 5,
}

func (x StorageChallengeDataStatus) String() string {
	return proto.EnumName(StorageChallengeDataStatus_name, int32(x))
}

func (StorageChallengeDataStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{0, 1}
}

type StorageChallengeMessageMessageType int32

const (
	StorageChallengeMessage_MessageType_UNKNOWN                               StorageChallengeMessageMessageType = 0
	StorageChallengeMessage_MessageType_STORAGE_CHALLENGE_CHALLENGE_MESSAGE   StorageChallengeMessageMessageType = 1
	StorageChallengeMessage_MessageType_STORAGE_CHALLENGE_RESPONSE_MESSAGE    StorageChallengeMessageMessageType = 2
	StorageChallengeMessage_MessageType_STORAGE_CHALLENGE_EVALUATION_MESSAGE  StorageChallengeMessageMessageType = 3
	StorageChallengeMessage_MessageType_STORAGE_CHALLENGE_AFFIRMATION_MESSAGE StorageChallengeMessageMessageType = 4
)

var StorageChallengeMessageMessageType_name = map[int32]string{
	0: "MessageType_UNKNOWN",
	1: "MessageType_STORAGE_CHALLENGE_CHALLENGE_MESSAGE",
	2: "MessageType_STORAGE_CHALLENGE_RESPONSE_MESSAGE",
	3: "MessageType_STORAGE_CHALLENGE_EVALUATION_MESSAGE",
	4: "MessageType_STORAGE_CHALLENGE_AFFIRMATION_MESSAGE",
}

var StorageChallengeMessageMessageType_value = map[string]int32{
	"MessageType_UNKNOWN":                               0,
	"MessageType_STORAGE_CHALLENGE_CHALLENGE_MESSAGE":   1,
	"MessageType_STORAGE_CHALLENGE_RESPONSE_MESSAGE":    2,
	"MessageType_STORAGE_CHALLENGE_EVALUATION_MESSAGE":  3,
	"MessageType_STORAGE_CHALLENGE_AFFIRMATION_MESSAGE": 4,
}

func (x StorageChallengeMessageMessageType) String() string {
	return proto.EnumName(StorageChallengeMessageMessageType_name, int32(x))
}

func (StorageChallengeMessageMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{5, 0}
}

type StorageChallengeData struct {
	MessageId                    string                             `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType                  StorageChallengeDataMessageType    `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=supernode.StorageChallengeDataMessageType" json:"message_type,omitempty"`
	ChallengeStatus              StorageChallengeDataStatus         `protobuf:"varint,3,opt,name=challenge_status,json=challengeStatus,proto3,enum=supernode.StorageChallengeDataStatus" json:"challenge_status,omitempty"`
	BlockNumChallengeSent        int32                              `protobuf:"varint,4,opt,name=block_num_challenge_sent,json=blockNumChallengeSent,proto3" json:"block_num_challenge_sent,omitempty"`
	BlockNumChallengeRespondedTo int32                              `protobuf:"varint,5,opt,name=block_num_challenge_responded_to,json=blockNumChallengeRespondedTo,proto3" json:"block_num_challenge_responded_to,omitempty"`
	BlockNumChallengeVerified    int32                              `protobuf:"varint,6,opt,name=block_num_challenge_verified,json=blockNumChallengeVerified,proto3" json:"block_num_challenge_verified,omitempty"`
	MerklerootWhenChallengeSent  string                             `protobuf:"bytes,7,opt,name=merkleroot_when_challenge_sent,json=merklerootWhenChallengeSent,proto3" json:"merkleroot_when_challenge_sent,omitempty"`
	ChallengingMasternodeId      string                             `protobuf:"bytes,8,opt,name=challenging_masternode_id,json=challengingMasternodeId,proto3" json:"challenging_masternode_id,omitempty"`
	RespondingMasternodeId       string                             `protobuf:"bytes,9,opt,name=responding_masternode_id,json=respondingMasternodeId,proto3" json:"responding_masternode_id,omitempty"`
	ChallengeFile                *StorageChallengeDataChallengeFile `protobuf:"bytes,10,opt,name=challenge_file,json=challengeFile,proto3" json:"challenge_file,omitempty"`
	ChallengeSliceCorrectHash    string                             `protobuf:"bytes,11,opt,name=challenge_slice_correct_hash,json=challengeSliceCorrectHash,proto3" json:"challenge_slice_correct_hash,omitempty"`
	ChallengeResponseHash        string                             `protobuf:"bytes,12,opt,name=challenge_response_hash,json=challengeResponseHash,proto3" json:"challenge_response_hash,omitempty"`
	ChallengeId                  string                             `protobuf:"bytes,13,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	PartialObservers             []string                           `protobuf:"bytes,14,rep,name=partial_observers,json=partialObservers,proto3" json:"partial_observers,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                           `json:"-"`
	XXX_unrecognized             []byte                             `json:"-"`
	XXX_sizecache                int32                              `json:"-"`
}

func (m *StorageChallengeData) Reset()         { *m = StorageChallengeData{} }
func (m *StorageChallengeData) String() string { return proto.CompactTextString(m) }
func (*StorageChallengeData) ProtoMessage()    {}
func (*StorageChallengeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{0}
}

func (m *StorageChallengeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChallengeData.Unmarshal(m, b)
}
func (m *StorageChallengeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChallengeData.Marshal(b, m, deterministic)
}
func (m *StorageChallengeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChallengeData.Merge(m, src)
}
func (m *StorageChallengeData) XXX_Size() int {
	return xxx_messageInfo_StorageChallengeData.Size(m)
}
func (m *StorageChallengeData) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChallengeData.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChallengeData proto.InternalMessageInfo

func (m *StorageChallengeData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *StorageChallengeData) GetMessageType() StorageChallengeDataMessageType {
	if m != nil {
		return m.MessageType
	}
	return StorageChallengeData_MessageType_UNKNOWN
}

func (m *StorageChallengeData) GetChallengeStatus() StorageChallengeDataStatus {
	if m != nil {
		return m.ChallengeStatus
	}
	return StorageChallengeData_Status_UNKNOWN
}

func (m *StorageChallengeData) GetBlockNumChallengeSent() int32 {
	if m != nil {
		return m.BlockNumChallengeSent
	}
	return 0
}

func (m *StorageChallengeData) GetBlockNumChallengeRespondedTo() int32 {
	if m != nil {
		return m.BlockNumChallengeRespondedTo
	}
	return 0
}

func (m *StorageChallengeData) GetBlockNumChallengeVerified() int32 {
	if m != nil {
		return m.BlockNumChallengeVerified
	}
	return 0
}

func (m *StorageChallengeData) GetMerklerootWhenChallengeSent() string {
	if m != nil {
		return m.MerklerootWhenChallengeSent
	}
	return ""
}

func (m *StorageChallengeData) GetChallengingMasternodeId() string {
	if m != nil {
		return m.ChallengingMasternodeId
	}
	return ""
}

func (m *StorageChallengeData) GetRespondingMasternodeId() string {
	if m != nil {
		return m.RespondingMasternodeId
	}
	return ""
}

func (m *StorageChallengeData) GetChallengeFile() *StorageChallengeDataChallengeFile {
	if m != nil {
		return m.ChallengeFile
	}
	return nil
}

func (m *StorageChallengeData) GetChallengeSliceCorrectHash() string {
	if m != nil {
		return m.ChallengeSliceCorrectHash
	}
	return ""
}

func (m *StorageChallengeData) GetChallengeResponseHash() string {
	if m != nil {
		return m.ChallengeResponseHash
	}
	return ""
}

func (m *StorageChallengeData) GetChallengeId() string {
	if m != nil {
		return m.ChallengeId
	}
	return ""
}

func (m *StorageChallengeData) GetPartialObservers() []string {
	if m != nil {
		return m.PartialObservers
	}
	return nil
}

type StorageChallengeDataChallengeFile struct {
	FileHashToChallenge      string   `protobuf:"bytes,1,opt,name=file_hash_to_challenge,json=fileHashToChallenge,proto3" json:"file_hash_to_challenge,omitempty"`
	ChallengeSliceStartIndex int64    `protobuf:"varint,2,opt,name=challenge_slice_start_index,json=challengeSliceStartIndex,proto3" json:"challenge_slice_start_index,omitempty"`
	ChallengeSliceEndIndex   int64    `protobuf:"varint,3,opt,name=challenge_slice_end_index,json=challengeSliceEndIndex,proto3" json:"challenge_slice_end_index,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *StorageChallengeDataChallengeFile) Reset()         { *m = StorageChallengeDataChallengeFile{} }
func (m *StorageChallengeDataChallengeFile) String() string { return proto.CompactTextString(m) }
func (*StorageChallengeDataChallengeFile) ProtoMessage()    {}
func (*StorageChallengeDataChallengeFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{0, 0}
}

func (m *StorageChallengeDataChallengeFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChallengeDataChallengeFile.Unmarshal(m, b)
}
func (m *StorageChallengeDataChallengeFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChallengeDataChallengeFile.Marshal(b, m, deterministic)
}
func (m *StorageChallengeDataChallengeFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChallengeDataChallengeFile.Merge(m, src)
}
func (m *StorageChallengeDataChallengeFile) XXX_Size() int {
	return xxx_messageInfo_StorageChallengeDataChallengeFile.Size(m)
}
func (m *StorageChallengeDataChallengeFile) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChallengeDataChallengeFile.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChallengeDataChallengeFile proto.InternalMessageInfo

func (m *StorageChallengeDataChallengeFile) GetFileHashToChallenge() string {
	if m != nil {
		return m.FileHashToChallenge
	}
	return ""
}

func (m *StorageChallengeDataChallengeFile) GetChallengeSliceStartIndex() int64 {
	if m != nil {
		return m.ChallengeSliceStartIndex
	}
	return 0
}

func (m *StorageChallengeDataChallengeFile) GetChallengeSliceEndIndex() int64 {
	if m != nil {
		return m.ChallengeSliceEndIndex
	}
	return 0
}

type ProcessStorageChallengeRequest struct {
	Data                 *StorageChallengeMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProcessStorageChallengeRequest) Reset()         { *m = ProcessStorageChallengeRequest{} }
func (m *ProcessStorageChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessStorageChallengeRequest) ProtoMessage()    {}
func (*ProcessStorageChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{1}
}

func (m *ProcessStorageChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessStorageChallengeRequest.Unmarshal(m, b)
}
func (m *ProcessStorageChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessStorageChallengeRequest.Marshal(b, m, deterministic)
}
func (m *ProcessStorageChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessStorageChallengeRequest.Merge(m, src)
}
func (m *ProcessStorageChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessStorageChallengeRequest.Size(m)
}
func (m *ProcessStorageChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessStorageChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessStorageChallengeRequest proto.InternalMessageInfo

func (m *ProcessStorageChallengeRequest) GetData() *StorageChallengeMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProcessStorageChallengeReply struct {
	Data                 *StorageChallengeMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProcessStorageChallengeReply) Reset()         { *m = ProcessStorageChallengeReply{} }
func (m *ProcessStorageChallengeReply) String() string { return proto.CompactTextString(m) }
func (*ProcessStorageChallengeReply) ProtoMessage()    {}
func (*ProcessStorageChallengeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{2}
}

func (m *ProcessStorageChallengeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessStorageChallengeReply.Unmarshal(m, b)
}
func (m *ProcessStorageChallengeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessStorageChallengeReply.Marshal(b, m, deterministic)
}
func (m *ProcessStorageChallengeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessStorageChallengeReply.Merge(m, src)
}
func (m *ProcessStorageChallengeReply) XXX_Size() int {
	return xxx_messageInfo_ProcessStorageChallengeReply.Size(m)
}
func (m *ProcessStorageChallengeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessStorageChallengeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessStorageChallengeReply proto.InternalMessageInfo

func (m *ProcessStorageChallengeReply) GetData() *StorageChallengeMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifyStorageChallengeRequest struct {
	Data                 *StorageChallengeMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *VerifyStorageChallengeRequest) Reset()         { *m = VerifyStorageChallengeRequest{} }
func (m *VerifyStorageChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyStorageChallengeRequest) ProtoMessage()    {}
func (*VerifyStorageChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{3}
}

func (m *VerifyStorageChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyStorageChallengeRequest.Unmarshal(m, b)
}
func (m *VerifyStorageChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyStorageChallengeRequest.Marshal(b, m, deterministic)
}
func (m *VerifyStorageChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyStorageChallengeRequest.Merge(m, src)
}
func (m *VerifyStorageChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyStorageChallengeRequest.Size(m)
}
func (m *VerifyStorageChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyStorageChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyStorageChallengeRequest proto.InternalMessageInfo

func (m *VerifyStorageChallengeRequest) GetData() *StorageChallengeMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifyStorageChallengeReply struct {
	Data                 *StorageChallengeData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VerifyStorageChallengeReply) Reset()         { *m = VerifyStorageChallengeReply{} }
func (m *VerifyStorageChallengeReply) String() string { return proto.CompactTextString(m) }
func (*VerifyStorageChallengeReply) ProtoMessage()    {}
func (*VerifyStorageChallengeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{4}
}

func (m *VerifyStorageChallengeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyStorageChallengeReply.Unmarshal(m, b)
}
func (m *VerifyStorageChallengeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyStorageChallengeReply.Marshal(b, m, deterministic)
}
func (m *VerifyStorageChallengeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyStorageChallengeReply.Merge(m, src)
}
func (m *VerifyStorageChallengeReply) XXX_Size() int {
	return xxx_messageInfo_VerifyStorageChallengeReply.Size(m)
}
func (m *VerifyStorageChallengeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyStorageChallengeReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyStorageChallengeReply proto.InternalMessageInfo

func (m *VerifyStorageChallengeReply) GetData() *StorageChallengeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type StorageChallengeMessage struct {
	MessageType          StorageChallengeMessageMessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=supernode.StorageChallengeMessageMessageType" json:"message_type,omitempty"`
	ChallengeId          string                             `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Data                 []byte                             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	SenderId             string                             `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderSignature      []byte                             `protobuf:"bytes,5,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *StorageChallengeMessage) Reset()         { *m = StorageChallengeMessage{} }
func (m *StorageChallengeMessage) String() string { return proto.CompactTextString(m) }
func (*StorageChallengeMessage) ProtoMessage()    {}
func (*StorageChallengeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b05b27bc9f20ae9f, []int{5}
}

func (m *StorageChallengeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChallengeMessage.Unmarshal(m, b)
}
func (m *StorageChallengeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChallengeMessage.Marshal(b, m, deterministic)
}
func (m *StorageChallengeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChallengeMessage.Merge(m, src)
}
func (m *StorageChallengeMessage) XXX_Size() int {
	return xxx_messageInfo_StorageChallengeMessage.Size(m)
}
func (m *StorageChallengeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChallengeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChallengeMessage proto.InternalMessageInfo

func (m *StorageChallengeMessage) GetMessageType() StorageChallengeMessageMessageType {
	if m != nil {
		return m.MessageType
	}
	return StorageChallengeMessage_MessageType_UNKNOWN
}

func (m *StorageChallengeMessage) GetChallengeId() string {
	if m != nil {
		return m.ChallengeId
	}
	return ""
}

func (m *StorageChallengeMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StorageChallengeMessage) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *StorageChallengeMessage) GetSenderSignature() []byte {
	if m != nil {
		return m.SenderSignature
	}
	return nil
}

func init() {
	proto.RegisterEnum("supernode.StorageChallengeDataMessageType", StorageChallengeDataMessageType_name, StorageChallengeDataMessageType_value)
	proto.RegisterEnum("supernode.StorageChallengeDataStatus", StorageChallengeDataStatus_name, StorageChallengeDataStatus_value)
	proto.RegisterEnum("supernode.StorageChallengeMessageMessageType", StorageChallengeMessageMessageType_name, StorageChallengeMessageMessageType_value)
	proto.RegisterType((*StorageChallengeData)(nil), "supernode.StorageChallengeData")
	proto.RegisterType((*StorageChallengeDataChallengeFile)(nil), "supernode.StorageChallengeData.challengeFile")
	proto.RegisterType((*ProcessStorageChallengeRequest)(nil), "supernode.ProcessStorageChallengeRequest")
	proto.RegisterType((*ProcessStorageChallengeReply)(nil), "supernode.ProcessStorageChallengeReply")
	proto.RegisterType((*VerifyStorageChallengeRequest)(nil), "supernode.VerifyStorageChallengeRequest")
	proto.RegisterType((*VerifyStorageChallengeReply)(nil), "supernode.VerifyStorageChallengeReply")
	proto.RegisterType((*StorageChallengeMessage)(nil), "supernode.StorageChallengeMessage")
}

func init() { proto.RegisterFile("storage_challenge.proto", fileDescriptor_b05b27bc9f20ae9f) }

var fileDescriptor_b05b27bc9f20ae9f = []byte{
	// 1005 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xed, 0x72, 0xdb, 0x44,
	0x17, 0xc7, 0x1f, 0xc5, 0x49, 0x5a, 0x1f, 0xa7, 0x89, 0x9e, 0x6d, 0x13, 0x2b, 0x2f, 0x2d, 0xc6,
	0xc3, 0x14, 0x77, 0x3a, 0x38, 0xc5, 0x81, 0x40, 0xe9, 0x30, 0x8c, 0x51, 0xe4, 0x54, 0x43, 0x22,
	0xa7, 0x92, 0x9d, 0x30, 0x7c, 0xd1, 0x28, 0xd6, 0xd6, 0x16, 0x91, 0xb5, 0x42, 0xbb, 0x6e, 0xf1,
	0xc5, 0xc0, 0x35, 0x70, 0x05, 0x7c, 0xe4, 0x62, 0xb8, 0x06, 0x3e, 0x30, 0x5a, 0xc9, 0x7a, 0x71,
	0xfc, 0x92, 0x01, 0xbe, 0x79, 0xcf, 0x39, 0xbf, 0xbf, 0xce, 0x9e, 0xb3, 0x67, 0xd7, 0x50, 0xa6,
	0x8c, 0x04, 0x56, 0x1f, 0x9b, 0xbd, 0x81, 0xe5, 0xba, 0xd8, 0xeb, 0xe3, 0xba, 0x1f, 0x10, 0x46,
	0x50, 0x91, 0x8e, 0x7c, 0x1c, 0x78, 0xc4, 0xc6, 0x7b, 0x5b, 0x3d, 0x32, 0x1c, 0x12, 0xcf, 0xa4,
	0x5e, 0xe4, 0xab, 0xfe, 0x5a, 0x82, 0x47, 0x46, 0xc4, 0xc9, 0x13, 0xec, 0xc4, 0x62, 0x16, 0x7a,
	0x0c, 0x30, 0xc4, 0x94, 0x86, 0x7a, 0x8e, 0x2d, 0x09, 0x15, 0xa1, 0x56, 0xd4, 0x8b, 0xb1, 0x45,
	0xb5, 0x91, 0x06, 0x1b, 0x13, 0x37, 0x1b, 0xfb, 0x58, 0x5a, 0xa9, 0x08, 0xb5, 0xcd, 0xc6, 0xf3,
	0x7a, 0xf2, 0xa9, 0xfa, 0x2c, 0xd5, 0x7a, 0xcc, 0x74, 0xc6, 0x3e, 0xd6, 0x4b, 0x99, 0x05, 0x7a,
	0x03, 0x62, 0x92, 0xb6, 0x49, 0x99, 0xc5, 0x46, 0x54, 0x2a, 0x70, 0xcd, 0xa7, 0xcb, 0x34, 0xa3,
	0x68, 0x7d, 0x2b, 0xe1, 0x0d, 0x6e, 0x40, 0x5f, 0x80, 0x74, 0xed, 0x92, 0xde, 0x8d, 0xe9, 0x8d,
	0x86, 0x66, 0x46, 0x1c, 0x7b, 0x4c, 0x5a, 0xad, 0x08, 0xb5, 0x35, 0x7d, 0x9b, 0xfb, 0xb5, 0xd1,
	0x30, 0x11, 0x34, 0xb0, 0xc7, 0x50, 0x0b, 0x2a, 0xb3, 0xc0, 0x00, 0x53, 0x9f, 0x78, 0x36, 0xb6,
	0x4d, 0x46, 0xa4, 0x35, 0x2e, 0x70, 0x70, 0x4b, 0x40, 0x9f, 0x04, 0x75, 0x08, 0xfa, 0x06, 0x0e,
	0x66, 0xe9, 0xbc, 0xc3, 0x81, 0xf3, 0xd6, 0xc1, 0xb6, 0xb4, 0xce, 0x35, 0x76, 0x6f, 0x69, 0x5c,
	0xc6, 0x01, 0x48, 0x86, 0x27, 0x43, 0x1c, 0xdc, 0xb8, 0x38, 0x20, 0x84, 0x99, 0xef, 0x07, 0xd8,
	0x9b, 0xde, 0xc7, 0x3d, 0xde, 0x97, 0xfd, 0x34, 0xea, 0x6a, 0x80, 0xbd, 0xfc, 0x6e, 0xbe, 0x82,
	0xdd, 0x09, 0xe4, 0x78, 0x7d, 0x73, 0x68, 0x51, 0x16, 0x55, 0x33, 0xec, 0xeb, 0x7d, 0xce, 0x97,
	0x33, 0x01, 0xe7, 0x89, 0x5f, 0xb5, 0xd1, 0x97, 0x20, 0xc5, 0xbb, 0xbe, 0x8d, 0x16, 0x39, 0xba,
	0x93, 0xfa, 0x73, 0x64, 0x07, 0x36, 0xd3, 0x54, 0xdf, 0x3a, 0x2e, 0x96, 0xa0, 0x22, 0xd4, 0x4a,
	0x8d, 0x4f, 0x96, 0x75, 0x33, 0xa1, 0x5a, 0x8e, 0x8b, 0xf5, 0x07, 0xb9, 0x65, 0x58, 0xd1, 0x4c,
	0x01, 0x5c, 0xa7, 0x87, 0xcd, 0x1e, 0x09, 0x02, 0xdc, 0x63, 0xe6, 0xc0, 0xa2, 0x03, 0xa9, 0xc4,
	0x73, 0xda, 0x4d, 0x4f, 0x42, 0x18, 0x22, 0x47, 0x11, 0xaf, 0x2d, 0x3a, 0x40, 0xc7, 0x50, 0x9e,
	0x6e, 0x28, 0xc5, 0x11, 0xbb, 0xc1, 0xd9, 0xed, 0x5e, 0xbe, 0x93, 0x14, 0x73, 0xee, 0x43, 0xd8,
	0x48, 0x39, 0xc7, 0x96, 0x1e, 0xf0, 0xe0, 0x52, 0x62, 0x53, 0x6d, 0xf4, 0x1c, 0xfe, 0xef, 0x5b,
	0x01, 0x73, 0x2c, 0xd7, 0x24, 0xd7, 0x14, 0x07, 0xef, 0x70, 0x40, 0xa5, 0xcd, 0x4a, 0xa1, 0x56,
	0xd4, 0xc5, 0xd8, 0xd1, 0x9e, 0xd8, 0xf7, 0x7e, 0x17, 0x60, 0x6a, 0x6b, 0x47, 0xb0, 0x13, 0x96,
	0x89, 0xe7, 0x62, 0x32, 0x92, 0x36, 0x3a, 0x9e, 0xbd, 0x87, 0xa1, 0x37, 0xcc, 0xa5, 0x43, 0x92,
	0x82, 0xa1, 0xaf, 0x61, 0x7f, 0xba, 0x1e, 0x94, 0x59, 0x01, 0x33, 0x1d, 0xcf, 0xc6, 0x3f, 0xf3,
	0xa1, 0x2c, 0xe8, 0x52, 0xbe, 0x1c, 0x46, 0x18, 0xa0, 0x86, 0x7e, 0xf4, 0x32, 0x3d, 0x1a, 0x13,
	0x1c, 0x7b, 0x76, 0x0c, 0x17, 0x38, 0xbc, 0x93, 0x87, 0x15, 0xcf, 0xe6, 0x68, 0xf5, 0x0f, 0x01,
	0x72, 0xf3, 0x5b, 0x86, 0x87, 0xe7, 0xe9, 0xd2, 0xec, 0x6a, 0xdf, 0x69, 0xed, 0x2b, 0x4d, 0xfc,
	0x1f, 0x6a, 0x40, 0x3d, 0xeb, 0x30, 0x3a, 0x6d, 0xbd, 0x79, 0xaa, 0x98, 0xf2, 0xeb, 0xe6, 0xd9,
	0x99, 0xa2, 0x9d, 0x2a, 0xa6, 0x6a, 0x18, 0xdd, 0xa6, 0x26, 0x2b, 0xe6, 0xb9, 0x62, 0x18, 0xcd,
	0x53, 0x45, 0x14, 0x96, 0x33, 0xba, 0x62, 0x5c, 0xb4, 0x35, 0x23, 0x65, 0x56, 0xd0, 0x31, 0x34,
	0x16, 0x33, 0x97, 0x8a, 0xae, 0xb6, 0x54, 0xb9, 0xd9, 0x51, 0xdb, 0x5a, 0xc2, 0x15, 0xaa, 0xbf,
	0x08, 0xb0, 0x1e, 0xdd, 0x20, 0x08, 0xc1, 0x66, 0x74, 0x75, 0x64, 0xd2, 0x4f, 0x6d, 0x17, 0x8a,
	0x76, 0xa2, 0x6a, 0xa7, 0xa2, 0x80, 0x1e, 0x81, 0x18, 0xdb, 0xa2, 0x3c, 0x4e, 0x94, 0x13, 0x71,
	0x25, 0x63, 0x35, 0xba, 0xb2, 0xac, 0x28, 0xa1, 0xb5, 0x80, 0x76, 0x61, 0x3b, 0xb6, 0xb6, 0x9a,
	0xea, 0x99, 0x72, 0x62, 0x76, 0xd4, 0x73, 0xa5, 0xdd, 0xed, 0x88, 0xab, 0xe8, 0x23, 0xa8, 0xe4,
	0x5d, 0xaa, 0x26, 0xb7, 0x75, 0x5d, 0x91, 0x3b, 0xc9, 0xfe, 0xc4, 0xb5, 0xea, 0xf7, 0xf0, 0xe4,
	0x22, 0x20, 0x3d, 0x4c, 0xe9, 0xf4, 0xb8, 0xe8, 0xf8, 0xa7, 0x11, 0xa6, 0x0c, 0x1d, 0xc3, 0xaa,
	0x6d, 0x31, 0x8b, 0x9f, 0x93, 0x52, 0xa3, 0xba, 0x60, 0xc0, 0xe2, 0x02, 0xe9, 0x3c, 0xbe, 0x7a,
	0x09, 0x07, 0x73, 0x95, 0x7d, 0x77, 0xfc, 0x8f, 0x75, 0xaf, 0xe0, 0x31, 0xbf, 0xc1, 0xc6, 0xff,
	0x75, 0xc2, 0x3a, 0xec, 0xcf, 0x13, 0x0e, 0xf3, 0x3d, 0xca, 0xc9, 0x7e, 0xb0, 0xe4, 0xa2, 0x89,
	0x35, 0xff, 0x2c, 0x40, 0x79, 0xce, 0x57, 0xd1, 0x9b, 0xa9, 0x37, 0x4e, 0xe0, 0xef, 0x51, 0x7d,
	0x79, 0xbe, 0xf3, 0x9f, 0xb9, 0xe9, 0x7b, 0x64, 0xe5, 0xf6, 0x3d, 0x82, 0xe2, 0x6d, 0x84, 0xf3,
	0xb7, 0x11, 0x65, 0x89, 0xf6, 0xa1, 0x48, 0xb1, 0x67, 0xe3, 0x20, 0x64, 0x56, 0x39, 0x73, 0x3f,
	0x32, 0xa8, 0x36, 0x7a, 0x06, 0x62, 0xec, 0xa4, 0x4e, 0xdf, 0xb3, 0xd8, 0x28, 0xc0, 0xfc, 0x79,
	0xda, 0xd0, 0xb7, 0x22, 0xbb, 0x31, 0x31, 0x57, 0xff, 0xba, 0xeb, 0xd4, 0x1e, 0xc1, 0xe1, 0xe2,
	0x69, 0x4a, 0x7f, 0xfd, 0xbb, 0xb1, 0xfd, 0x0c, 0x5e, 0x2c, 0x66, 0x94, 0xcb, 0xe6, 0x59, 0x77,
	0x6a, 0x68, 0xd1, 0xe7, 0xf0, 0xe9, 0x62, 0xaa, 0xd9, 0x6a, 0xa9, 0xfa, 0x79, 0x1e, 0x5b, 0x6d,
	0xfc, 0xb6, 0x12, 0xce, 0x68, 0xbe, 0x65, 0xa8, 0x09, 0xf7, 0x0c, 0x4c, 0xa9, 0x43, 0x3c, 0xb4,
	0x9b, 0x6d, 0x6d, 0x64, 0x8b, 0xcf, 0xec, 0x5e, 0x79, 0x96, 0xcb, 0x77, 0xc7, 0x35, 0xe1, 0x85,
	0x80, 0x86, 0x50, 0x9e, 0x33, 0x49, 0xe8, 0x59, 0x86, 0x5b, 0x3c, 0xc7, 0x7b, 0x1f, 0xdf, 0x25,
	0x34, 0x3c, 0xe8, 0x3f, 0xc2, 0xce, 0xec, 0x39, 0x40, 0xb5, 0x8c, 0xc4, 0xc2, 0x19, 0xdc, 0x7b,
	0x7a, 0x87, 0x48, 0xdf, 0x1d, 0x7f, 0xfb, 0xea, 0x87, 0x97, 0x7d, 0x87, 0x0d, 0x46, 0xd7, 0xf5,
	0x1e, 0x19, 0x1e, 0xfa, 0xe1, 0x13, 0xef, 0x7a, 0x98, 0xbd, 0x27, 0xc1, 0xcd, 0x61, 0x9f, 0x84,
	0xf8, 0x21, 0xff, 0x23, 0x79, 0x98, 0xc8, 0xbd, 0x4a, 0x7e, 0x5d, 0xaf, 0x73, 0xd7, 0xd1, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x04, 0x0b, 0x01, 0x9a, 0x0a, 0x00, 0x00,
}
