version: "3.7"

x-restart: &restart_policy
  restart: "${COMPOSE_RESTART_BEHAVIOR:-on-failure}"
x-network: &network
  networks:
    - internal
x-default: &default
  <<: *restart_policy
  <<: *network

services:
  sn1:
    <<: *default
    container_name: snserver-1
    hostname: snserver-1
    image: gonode-sn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    build:
      context: ..
      dockerfile: ./integration/sn.it.Dockerfile
    command: sh -c "/app/app --config-file=/configs/sn1.yml --pastel-config-file=/configs/pastel.conf"
    ports:
      - 19090:9090
  sn2:
    <<: *default
    container_name: snserver-2
    hostname: snserver-2
    image: gonode-sn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    depends_on:
      - sn1
    command: sh -c "/app/app --config-file=/configs/sn2.yml --pastel-config-file=/configs/pastel.conf"
    ports:
      - 19091:9090
  sn3:
    <<: *default
    container_name: snserver-3
    hostname: snserver-3
    image: gonode-sn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    depends_on:
      - sn1
    command: sh -c "/app/app --config-file=/configs/sn3.yml --pastel-config-file=/configs/pastel.conf"
    ports:
      - 19092:9090
networks:
  internal: {}
  