version: "3.7"

x-restart: &restart_policy
  restart: "${COMPOSE_RESTART_BEHAVIOR:-on-failure}"
x-network: &network
  networks:
    - internal
x-default: &default
  <<: *restart_policy
  <<: *network

services:
  wn:
    <<: *default
    container_name: walletnode-1
    hostname: walletnode-1
    image: gonode-wn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    build:
      context: ..
      dockerfile: ./integration/wn.it.Dockerfile
    command: sh -c "/app/app --config-file=/configs/wn.yml --pastel-config-file=/configs/p4.conf"
    ports:
      - 18089:8089
  sn1:
    <<: *default
    container_name: snserver-1
    hostname: snserver-1
    image: gonode-sn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    build:
      context: ..
      dockerfile: ./integration/sn.it.Dockerfile
    command: sh -c "/app/app --config-file=/configs/sn1.yml --pastel-config-file=/configs/p1.conf"
    ports:
      - 19090:9090
  sn2:
    <<: *default
    container_name: snserver-2
    hostname: snserver-2
    image: gonode-sn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    depends_on:
      - sn1
    command: sh -c "/app/app --config-file=/configs/sn2.yml --pastel-config-file=/configs/p2.conf"
    ports:
      - 19091:9090
  sn3:
    <<: *default
    container_name: snserver-3
    hostname: snserver-3
    image: gonode-sn-service:0.1
    environment:
      - INTEGRATION_TEST_ENV=true
    depends_on:
      - sn1
    command: sh -c "/app/app --config-file=/configs/sn3.yml --pastel-config-file=/configs/p3.conf"
    ports:
      - 19092:9090
  dd-server-1:
    <<: *default
    container_name: dd-server-1
    hostname: dd-server-1
    image: gonode-dd-server:0.1
    build:
      context: ..
      dockerfile: ./integration/dd.it.Dockerfile
    command: sh -c "/app/app"
    ports:
      - 51052:51052
  dd-server-2:
    <<: *default
    container_name: dd-server-2
    hostname: dd-server-2
    image: gonode-dd-server:0.1
    command: sh -c "/app/app"
    ports:
      - 52052:51052
  dd-server-3:
    <<: *default
    container_name: dd-server-3
    hostname: dd-server-3
    image: gonode-dd-server:0.1
    command: sh -c "/app/app"
    ports:
      - 53052:51052
  rq-server-1:
    <<: *default
    container_name: rq-server-1
    hostname: rq-server-1
    image: gonode-rq-server:0.1
    build:
      context: ..
      dockerfile: ./integration/rq.it.Dockerfile
    command: sh -c "/app/app"
    ports:
      - 51051:51051
  rq-server-2:
    <<: *default
    container_name: rq-server-2
    hostname: rq-server-2
    image: gonode-rq-server:0.1
    command: sh -c "/app/app"
    ports:
      - 52051:51051
  rq-server-3:
    <<: *default
    container_name: rq-server-3
    hostname: rq-server-3
    image: gonode-rq-server:0.1
    command: sh -c "/app/app"
    ports:
      - 53051:51051
  rq-server-4:
    <<: *default
    container_name: rq-server-4
    hostname: rq-server-4
    image: gonode-rq-server:0.1
    command: sh -c "/app/app"
    ports:
      - 54051:51051
  pasteld-1:
    <<: *default
    container_name: pasteld-1
    hostname: pasteld-1
    image: gonode-pasteld:0.1
    build:
      context: ..
      dockerfile: ./integration/pastel.it.Dockerfile
    command: sh -c "/app/app"
    ports:
      - 29931:29932
  pasteld-2:
    <<: *default
    container_name: pasteld-2
    hostname: pasteld-2
    image: gonode-pasteld:0.1
    command: sh -c "/app/app"
    ports:
      - 29932:29932
  pasteld-3:
    <<: *default
    container_name: pasteld-3
    hostname: pasteld-3
    image: gonode-pasteld:0.1
    command: sh -c "/app/app"
    ports:
      - 29933:29932
  pasteld-4:
    <<: *default
    container_name: pasteld-4
    hostname: pasteld-4
    image: gonode-pasteld:0.1
    command: sh -c "/app/app"
    ports:
      - 29934:29932
networks:
  internal: {}
  