pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4450"
  password: ""

node:
  pastel_id: jXXUt9LXpByGYPZ21Hdofw267Axjff6RPFxQJRgcVe19vCimuYD2zMyGaUucNCpZWDrthSj4Jy5dAevNZqALW4
  server:
    listen_addresses: "0.0.0.0"
    port: 4450

p2p:
  listen_address: "0.0.0.0"
  port: 6006
  data_dir: "p2p-localnet-6006"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: true
  exposed_address: "0.0.0.0:4101"
  listen_address: "0.0.0.0"
  http_port: 4101
  raft_port: 4102
  data_dir: "metadb-4450"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  write-template-path: ../metadb/database/commands/user_info_write.tmpl
  query-template-path: ../metadb/database/commands/user_info_query.tmpl
