# please provide pastel configs in pastel.conf
log-config:
  log-file:             # e.g: logs.json - by default, logs are only written to stdout
  log-compress: true    # compress log or not
  log-max-size-mb: 100   # maximum log file size before rotate to new file
  log-max-age-days: 3   # maximum duration to retain old log files based on the timestamp encoded in their filename
  log-max-backups: 10   # set the maximum number of old log files to retain
  log-levels:           # log level of individual files 
    common: debug
    p2p: info
    metadb: info
    dd: info
quiet: false
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id: jXZDyPoescC4pgWMeD2qMzyPi5gaxMkkggrwGFAK2izTQgEkrjKqHSbG1HCfCFY9n3pAQ9q4VFHLrakL89bvfR
  pass_phrase: "passphrase"
  server:
    listen_addresses: "0.0.0.0"
    port: 4447

p2p:
  listen_address: "0.0.0.0"
  port: 6003
  data_dir: "p2p-localnet-6003"

metadb:
  is_leader: false
  none_voter: true
  listen_address: "0.0.0.0"
  http_port: 4071
  raft_port: 4072
  data_dir: "metadb-4447"
  block_interval: 48

raptorq:
  host: "localhost"
  port: 50054
