pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4447"
  password: ""

node:
  pastel_id: jXZDyPoescC4pgWMeD2qMzyPi5gaxMkkggrwGFAK2izTQgEkrjKqHSbG1HCfCFY9n3pAQ9q4VFHLrakL89bvfR
  server:
    listen_addresses: "0.0.0.0"
    port: 4447
  userdata_process:
    number_super_nodes: 3
    minimal_node_confirm_success: 2

p2p:
  listen_address: "0.0.0.0"
  port: 6003
  data_dir: "p2p-localnet-6003"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: true
  exposed_address: "0.0.0.0:4071"
  listen_address: "0.0.0.0"
  http_port: 4071
  raft_port: 4072
  data_dir: "metadb-4447"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  write-template-path: ../metadb/database/commands/user_info_write.tmpl
  query-template-path: ../metadb/database/commands/user_info_query.tmpl
