pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4452"
  password: ""

node:
  pastel_id: jXXUqnouGD5Qgf4JPQWfJPe4fU4jbmiXTUWD9dFuTMwh8KrQDo3kdgWnKBfLA41dxS7x7iABX98vS7CdKopz6e
  server:
    listen_addresses: "0.0.0.0"
    port: 4452

p2p:
  listen_address: "0.0.0.0"
  port: 6008
  data_dir: "p2p-localnet-6008"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: true
  exposed_address: "0.0.0.0:4121"
  listen_address: "0.0.0.0"
  http_port: 4121
  raft_port: 4122
  data_dir: "metadb-4452"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  write-template-path: ../metadb/database/commands/user_info_write.tmpl
  query-template-path: ../metadb/database/commands/user_info_query.tmpl
