# please provide pastel configs in pastel.conf
log-level: info
log-file:  # e.g: logs.json - by default, logs are only written to stdout
quiet: false
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id: jXYUbc59imKKoSNFdu7BcNbCBULS21MBBe8GjzfRXi9vGZrXV1y7ihJwY9ib8xTB8cSnsatvNroNJ8b7DN4Rrd
  pass_phrase: "passphrase"
  server:
    listen_addresses: "0.0.0.0"
    port: 4446

p2p:
  listen_address: "0.0.0.0"
  port: 6002
  data_dir: "p2p-localnet-6002"

metadb:
  is_leader: false
  none_voter: false
  listen_address: "0.0.0.0"
  http_port: 4061
  raft_port: 4062
  data_dir: "metadb-4446"

raptorq:
  host: "localhost"
  port: 50053
