pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4448"
  password: ""

node:
  pastel_id: jXY63MoCoHzu7sL8azPKFuqaXJNDZ48rceUXkNr6kXR8PCfK8Cg6tNvX77TKRgu17istzkq6CkcwAwLFvAqrv8
  server:
    listen_addresses: "0.0.0.0"
    port: 4448

p2p:
  listen_address: "0.0.0.0"
  port: 6004
  data_dir: "p2p-localnet-6004"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: true
  exposed_address: "0.0.0.0:4081"
  listen_address: "0.0.0.0"
  http_port: 4081
  raft_port: 4082
  data_dir: "metadb-4448"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  write-template-path: ../metadb/database/commands/user_info_write.tmpl
  query-template-path: ../metadb/database/commands/user_info_query.tmpl
