pastel-api:
  hostname: "127.0.0.1"
  port: 12158
  username: "rt"
  password: "rt"

node:
  pastel_id: jXaMnqwbdCFhNJFDhTPGryxxB8brGkAZ14qVzywRB9jahNEZDKQZwquUzaQt7gFKPppi7rXYKxWobhbFvL2R2M 
  pass_phrase: "passphrase"
  server:
    listen_addresses: "0.0.0.0"
    port: 4446

p2p:
  listen_address: "0.0.0.0"
  port: 6002
  data_dir: "p2p-localnet-6002"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  listen_address: "0.0.0.0"
  http_port: 4061
  raft_port: 4062
  data_dir: "metadb-4446"

raptorq:
  hostname: "localhost"
  port: 50053
