pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4449"
  password: ""

node:
  pastel_id: jXZpHRtXYWQerHut9MrhUed9WGGbwSCJxdAJX6A5ALK2kiYtFfMZCs6NGLsdNKvmWcjfAhQkgTGsbvsodcvSND
  server:
    listen_addresses: "0.0.0.0"
    port: 4449

p2p:
  listen_address: "0.0.0.0"
  port: 6005
  data_dir: "p2p-localnet-6005"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: true
  exposed_address: "0.0.0.0:4091"
  listen_address: "0.0.0.0"
  http_port: 4091
  raft_port: 4092
  data_dir: "metadb-4449"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  write-template-path: ../metadb/database/commands/user_info_write.tmpl
  query-template-path: ../metadb/database/commands/user_info_query.tmpl
