pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4451"
  password: ""

node:
  pastel_id: jXaSeRsfnZjQSCqb56vBVZ4CmJJRG3d9V6shgVXKWKFkL9kcX1zqnznCjRLfkNMhvgnX18nK4SRFiDQVYfrcvZ
  server:
    listen_addresses: "0.0.0.0"
    port: 4451

p2p:
  listen_address: "0.0.0.0"
  port: 6007
  data_dir: "p2p-localnet-6007"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: true
  exposed_address: "0.0.0.0:4111"
  listen_address: "0.0.0.0"
  http_port: 4111
  raft_port: 4112
  data_dir: "metadb-4451"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  write-template-path: ../metadb/database/commands/user_info_write.tmpl
  query-template-path: ../metadb/database/commands/user_info_query.tmpl
