# please provide pastel configs in pastel.conf
log-levels:
  common: info
  p2p: error
  metadb: error
  dd: error
log-file:  # e.g: logs.json - by default, logs are only written to stdout
quiet: false
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id: jXZDyPoescC4pgWMeD2qMzyPi5gaxMkkggrwGFAK2izTQgEkrjKqHSbG1HCfCFY9n3pAQ9q4VFHLrakL89bvfR
  pass_phrase: "passphrase"
  server:
    listen_addresses: "0.0.0.0"
    port: 4447

p2p:
  listen_address: "0.0.0.0"
  port: 6003
  data_dir: "p2p-localnet-6003"

metadb:
  is_leader: false
  none_voter: true
  listen_address: "0.0.0.0"
  http_port: 4071
  raft_port: 4072
  data_dir: "metadb-4447"
  block_interval: 48

raptorq:
  host: "localhost"
  port: 50054
