pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "rt"
  password: "rt"

node:
  pastel_id: jXaMnqwbdCFhNJFDhTPGryxxB8brGkAZ14qVzywRB9jahNEZDKQZwquUzaQt7gFKPppi7rXYKxWobhbFvL2R2M 
  pass_phrase: "passphrase"
  preburnt_tx_min_confirmation: 3
  # Timeout in minutes
  preburnt_tx_confirmation_timeout: 8 
  server:
    listen_addresses: "0.0.0.0"
    port: 4446

p2p:
  listen_address: "0.0.0.0"
  port: 6002
  data_dir: "p2p-localnet-6002"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: false
  exposed_address: "0.0.0.0:4061"
  listen_address: "0.0.0.0"
  http_port: 4061
  raft_port: 4062
  data_dir: "metadb-4446"

userdb:
  schema-path: ../metadb/database/commands/schema.sql
  template-path: ../metadb/database/commands

raptorq:
  hostname: "localhost"
  port: 50053

dupe-detection:
  input_dir: "input"
  output_dir: "output"
  data_file: "dupe_detection_image_fingerprint_database.sqlite"
