# please provide pastel configs in pastel.conf
log-level: info
log-file:  # e.g: logs.json - by default, logs are only written to stdout
quiet: false
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id: jXYUbc59imKKoSNFdu7BcNbCBULS21MBBe8GjzfRXi9vGZrXV1y7ihJwY9ib8xTB8cSnsatvNroNJ8b7DN4Rrd
  pass_phrase: "passphrase"
  number_connected_nodes: 2   # artwork reg
  preburnt_tx_min_confirmation: 3
  preburnt_tx_confirmation_timeout: 8   # Timeout in minutes
  server:
    listen_addresses: "0.0.0.0"
    port: 4446
  raptorq_service: # artwork download raptorq service addr
  number_super_nodes: 3   # userdata_process
  minimal_node_confirm_success: 2   # userdata_process

p2p:
  listen_address: "0.0.0.0"
  port: 6002
  data_dir: "p2p-localnet-6002"
  bootstrap_ip: "localhost"
  bootstrap_port: 6000

metadb:
  is_leader: false
  none_voter: false
  exposed_address: "0.0.0.0:4061"
  listen_address: "0.0.0.0"
  http_port: 4061
  raft_port: 4062
  data_dir: "metadb-4446"

raptorq:
  host: "localhost"
  port: 50053

dupe-detection:
  input_dir: "input"
  output_dir: "output"
  data_file: "dupe_detection_image_fingerprint_database.sqlite"
  # timeout when waiting for output from dupe detection service in second
  timeout: 300
