log-config:
  log-file:             # e.g: logs.json - by default, logs are only written to stdout
  log-compress: true    # compress log or not
  log-max-size-mb: 100   # maximum log file size before rotate to new file
  log-max-age-days: 3   # maximum duration to retain old log files based on the timestamp encoded in their filename
  log-max-backups: 10   # set the maximum number of old log files to retain
  log-levels:           # log level of individual files 
    common: debug
    p2p: info
    metadb: info
    dd: info
quiet:
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id:
  pass_phrase: 
  server:
    listen_addresses: "0.0.0.0"
    port: 4444

p2p:
  listen_address: "0.0.0.0"
  port: 6000
  data_dir: "p2p"

metadb:
  is_leader: false
  none_voter: true
  listen_address: "0.0.0.0"
  http_port: 4001
  raft_port: 4002
  data_dir: "metadb"
  block_interval: 48

raptorq:
  host: "localhost"
  port: 50051

dd-server:
  host: "localhost"
  port: 50052
  dd-temp-file-dir: "dd-server"

debug-service:
  http-port: 9090