log-level:
p2p-log-level:
metadb-log-level:
log-file:
quiet:
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id:
  pass_phrase: 
  server:
    listen_addresses: "0.0.0.0"
    port: 4444

p2p:
  listen_address: "0.0.0.0"
  port: 6000
  data_dir: "p2p"

metadb:
  is_leader: false
  none_voter: true
  listen_address: "0.0.0.0"
  http_port: 4001
  raft_port: 4002
  data_dir: "metadb"
  block_interval: 48

raptorq:
  host: "localhost"
  port: 50051

dd-server:
  host: "localhost"
  port: 50052
  dd-temp-file-dir: "dd-server"

debug-service:
  http-port: 9090