log-level:
log-file:
quiet:
temp-dir:
work-dir:
rq-files-dir: 
dd-service-dir:

node:
  pastel_id:
  pass_phrase: 
  server:
    listen_addresses: "0.0.0.0"
    port:

p2p:
  listen_address: "0.0.0.0"
  port: 
  data_dir: "p2p"

metadb:
  is_leader: false
  none_voter: true
  listen_address: 
  http_port: 
  raft_port: 
  data_dir: "metadb"

raptorq:
  host: "localhost"
  port: 
