pastel-api:
  port: 19932

node:
  # `pastel_id` must match to active `PastelID` from masternode.
  # To check it out first get the active outpoint from `masteronde status`, then filter the result of `tickets list id mine` by this outpoint.
  pastel_id: jXXk5k99wK1ca5ZqC6cXSwiiUv57NNiEAApUBtQCNYPbgXDTVwo1k4vVb8J9CAMtnUC4QrNED4DhUGqKyEZCQS
  server:
    # `listen_address` and `port` must match to `extAddress` from masternode.conf
    listen_addresses: "127.0.0.1"
    port: 4444
  rqlite:
    http_address: "localhost:4001"
    raft_address: "localhost:4002"
    node_id: "1"
    data_dir: "data/node1"
    raft_open_timeout: "5s"

